<?php

use Illuminate\Database\Seeder;

class BaseDatosCursosTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('base_datos_cursos')->delete();
        
        \DB::table('base_datos_cursos')->insert(array (
            0 => 
            array (
                'id' => 1,
                'Nombre_del_curso' => 'Cajero       ',
                'Sector' => 'Comercio y servicios',
                'Nombre_del_centro' => 'Hogar Zacarías Guerra',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 140,
                'inicio' => '9/24/2018',
                'fin' => '11/9/2018',
                'ao' => 2018,
                'costo_por_participante_USD' => NULL,
                'Nombre_del_instructor' => 'Rigoberto Castellón',
                'cupos_por_curso' => 22,
                'H' => 9,
                'M' => 13,
                'total' => 22,
            ),
            1 => 
            array (
                'id' => 2,
                'Nombre_del_curso' => 'Cocina básica',
                'Sector' => 'Gastronomía',
                'Nombre_del_centro' => 'Hogar Zacarías Guerra',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 140,
                'inicio' => '9/24/2018',
                'fin' => '11/9/2018',
                'ao' => 2018,
                'costo_por_participante_USD' => NULL,
                'Nombre_del_instructor' => 'Luis Salvador Enrique Neyra',
                'cupos_por_curso' => 23,
                'H' => 6,
                'M' => 12,
                'total' => 18,
            ),
            2 => 
            array (
                'id' => 3,
                'Nombre_del_curso' => 'Cocina básica',
                'Sector' => 'Gastronomía',
                'Nombre_del_centro' => 'Hogar Zacarías Guerra',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 140,
                'inicio' => '11/5/2018',
                'fin' => '12/17/2018',
                'ao' => 2018,
                'costo_por_participante_USD' => NULL,
                'Nombre_del_instructor' => 'Luis Salvador Enrique Neyra',
                'cupos_por_curso' => 20,
                'H' => 8,
                'M' => 12,
                'total' => 20,
            ),
            3 => 
            array (
                'id' => 4,
                'Nombre_del_curso' => 'Corte y confección',
                'Sector' => 'Textil-Vestuario',
                'Nombre_del_centro' => 'Hogar Zacarías Guerra',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 140,
                'inicio' => '9/24/2018',
                'fin' => '11/9/2018',
                'ao' => 2018,
                'costo_por_participante_USD' => NULL,
                'Nombre_del_instructor' => 'Gertrudis Velásquez',
                'cupos_por_curso' => 20,
                'H' => 2,
                'M' => 13,
                'total' => 15,
            ),
            4 => 
            array (
                'id' => 5,
                'Nombre_del_curso' => 'Corte y confección',
                'Sector' => 'Textil-Vestuario',
                'Nombre_del_centro' => 'Hogar Zacarías Guerra',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 140,
                'inicio' => '11/5/2018',
                'fin' => '12/17/2018',
                'ao' => 2018,
                'costo_por_participante_USD' => NULL,
                'Nombre_del_instructor' => 'Karena Margarita Mora Chavarría',
                'cupos_por_curso' => 20,
                'H' => 2,
                'M' => 17,
                'total' => 19,
            ),
            5 => 
            array (
                'id' => 6,
                'Nombre_del_curso' => 'Soldadura',
                'Sector' => 'Industria y construcción',
                'Nombre_del_centro' => 'Centro Juvenil Don Bosco',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 220,
                'inicio' => '9/17/2018',
                'fin' => '11/30/2018',
                'ao' => 2018,
                'costo_por_participante_USD' => NULL,
                'Nombre_del_instructor' => 'Fernando Daniel Carrillo',
                'cupos_por_curso' => 20,
                'H' => 16,
                'M' => 1,
                'total' => 17,
            ),
            6 => 
            array (
                'id' => 7,
                'Nombre_del_curso' => 'Panadería y bollería',
                'Sector' => 'Agroindustria',
                'Nombre_del_centro' => 'Centro Juvenil Don Bosco',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 220,
                'inicio' => '9/17/2018',
                'fin' => '11/30/2018',
                'ao' => 2018,
                'costo_por_participante_USD' => NULL,
                'Nombre_del_instructor' => 'Martha Verónica Téllez',
                'cupos_por_curso' => NULL,
                'H' => 12,
                'M' => 6,
                'total' => 18,
            ),
            7 => 
            array (
                'id' => 8,
                'Nombre_del_curso' => 'Corte de cabello y barbería',
                'Sector' => 'Comercio y servicios',
                'Nombre_del_centro' => 'Centro Juvenil Don Bosco',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 90,
                'inicio' => '9/22/2018',
                'fin' => '11/24/2018',
                'ao' => 2018,
                'costo_por_participante_USD' => NULL,
                'Nombre_del_instructor' => 'Meyling Hernández ',
                'cupos_por_curso' => NULL,
                'H' => 10,
                'M' => 6,
                'total' => 16,
            ),
            8 => 
            array (
                'id' => 9,
                'Nombre_del_curso' => 'Reparación de motores de combustión interna',
                'Sector' => 'Automotriz',
                'Nombre_del_centro' => 'Colegio Roberto Clemente Fe y Alegría',
                'municipio' => 'Ciudad Sandino',
                'depto' => 'Managua',
                'carga_horaria' => 212,
                'inicio' => '9/20/2018',
                'fin' => '12/2/2018',
                'ao' => 2018,
                'costo_por_participante_USD' => NULL,
                'Nombre_del_instructor' => 'Nicolás Martínez ',
                'cupos_por_curso' => NULL,
                'H' => 19,
                'M' => 1,
                'total' => 20,
            ),
            9 => 
            array (
                'id' => 10,
                'Nombre_del_curso' => 'Electricidad automotriz',
                'Sector' => 'Automotriz',
                'Nombre_del_centro' => 'Colegio Roberto Clemente Fe y Alegría',
                'municipio' => 'Ciudad Sandino',
                'depto' => 'Managua',
                'carga_horaria' => 280,
                'inicio' => '9/17/2018',
                'fin' => '12/8/2018',
                'ao' => 2018,
                'costo_por_participante_USD' => NULL,
                'Nombre_del_instructor' => 'Edison Flores',
                'cupos_por_curso' => NULL,
                'H' => 18,
                'M' => 1,
                'total' => 19,
            ),
            10 => 
            array (
                'id' => 11,
                'Nombre_del_curso' => 'Electricidad residencial',
                'Sector' => 'Industria y construcción',
                'Nombre_del_centro' => 'Colegio Roberto Clemente Fe y Alegría',
                'municipio' => 'Ciudad Sandino',
                'depto' => 'Managua',
                'carga_horaria' => 184,
                'inicio' => '9/19/2018',
                'fin' => '12/5/2018',
                'ao' => 2018,
                'costo_por_participante_USD' => NULL,
                'Nombre_del_instructor' => 'Felipe Josue Ulloa Díaz',
                'cupos_por_curso' => NULL,
                'H' => 11,
                'M' => 3,
                'total' => 14,
            ),
            11 => 
            array (
                'id' => 12,
                'Nombre_del_curso' => 'Soldadura oxiacetilénica, oxicorte y corte con plasma',
                'Sector' => 'Industria y construcción',
                'Nombre_del_centro' => 'Instituto Politécnico La Salle',
                'municipio' => 'León',
                'depto' => 'León',
                'carga_horaria' => NULL,
                'inicio' => '9/1/2018',
                'fin' => '12/16/2018',
                'ao' => 2018,
                'costo_por_participante_USD' => NULL,
                'Nombre_del_instructor' => 'William López Centeno',
                'cupos_por_curso' => NULL,
                'H' => 23,
                'M' => 4,
                'total' => 27,
            ),
            12 => 
            array (
                'id' => 13,
                'Nombre_del_curso' => 'Mantenimiento equipos línea marrón',
                'Sector' => 'Comercio y servicios',
                'Nombre_del_centro' => 'Instituto Politécnico La Salle',
                'municipio' => 'León',
                'depto' => 'León',
                'carga_horaria' => NULL,
                'inicio' => '9/1/2018',
                'fin' => '1/27/2019',
                'ao' => 2018,
                'costo_por_participante_USD' => NULL,
                'Nombre_del_instructor' => 'Armando Coulson',
                'cupos_por_curso' => NULL,
                'H' => 8,
                'M' => 2,
                'total' => 10,
            ),
            13 => 
            array (
                'id' => 14,
                'Nombre_del_curso' => 'Mantenimiento y reparación de sistemas de mandos',
                'Sector' => 'Automotriz',
                'Nombre_del_centro' => 'Instituto Politécnico La Salle',
                'municipio' => 'León',
                'depto' => 'León',
                'carga_horaria' => NULL,
                'inicio' => '9/1/2018',
                'fin' => '12/16/2018',
                'ao' => 2018,
                'costo_por_participante_USD' => NULL,
                'Nombre_del_instructor' => 'Juan Francisco Iglesias',
                'cupos_por_curso' => NULL,
                'H' => 28,
                'M' => 0,
                'total' => 28,
            ),
            14 => 
            array (
                'id' => 15,
                'Nombre_del_curso' => 'Corte y confección prendas damas y caballero',
                'Sector' => 'Textil-Vestuario',
                'Nombre_del_centro' => 'Academia Korisa',
                'municipio' => 'Diriamba',
                'depto' => 'Carazo',
                'carga_horaria' => 288,
                'inicio' => '6/1/2019',
                'fin' => '11/23/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 211.0,
                'Nombre_del_instructor' => 'Marlee Rodriguez/Kora Gaitan',
                'cupos_por_curso' => NULL,
                'H' => 1,
                'M' => 17,
                'total' => 22,
            ),
            15 => 
            array (
                'id' => 16,
                'Nombre_del_curso' => 'Corte y confección con técnicas creativas e innovadoras',
                'Sector' => 'Textil-Vestuario',
                'Nombre_del_centro' => 'Academia Korisa',
                'municipio' => 'Diriamba',
                'depto' => 'Carazo',
                'carga_horaria' => 159,
                'inicio' => '6/4/2019',
                'fin' => '8/23/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 182.0,
                'Nombre_del_instructor' => 'Kora Gaitan',
                'cupos_por_curso' => NULL,
                'H' => NULL,
                'M' => 15,
                'total' => 17,
            ),
            16 => 
            array (
                'id' => 17,
                'Nombre_del_curso' => 'Corte y confección uniformes escolares y trajes folclóricos',
                'Sector' => 'Textil-Vestuario',
                'Nombre_del_centro' => 'Academia Korisa',
                'municipio' => 'Diriamba',
                'depto' => 'Carazo',
                'carga_horaria' => 134,
                'inicio' => '7/25/2019',
                'fin' => '10/30/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 132.95,
                'Nombre_del_instructor' => 'Evelin Flores/Kora Gaitan',
                'cupos_por_curso' => NULL,
                'H' => NULL,
                'M' => 17,
                'total' => 19,
            ),
            17 => 
            array (
                'id' => 18,
                'Nombre_del_curso' => 'Corte y confección prendas para caballeros',
                'Sector' => 'Textil-Vestuario',
                'Nombre_del_centro' => 'Academia Korisa',
                'municipio' => 'Diriamba',
                'depto' => 'Carazo',
                'carga_horaria' => 164,
                'inicio' => '8/27/2019',
                'fin' => '11/22/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 134.45,
                'Nombre_del_instructor' => 'Marlee Rodriguez/Kora Gaitan',
                'cupos_por_curso' => NULL,
                'H' => 3,
                'M' => 17,
                'total' => 22,
            ),
            18 => 
            array (
                'id' => 19,
                'Nombre_del_curso' => 'Mantenimiento preventivo básico maquinaria pesada',
                'Sector' => 'Industria y construcción',
                'Nombre_del_centro' => 'Centro de capacitación NIMAC',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 112,
                'inicio' => '5/27/2019',
                'fin' => '6/11/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 955.75,
                'Nombre_del_instructor' => 'Darling Silva/Eddy Gonzalez',
                'cupos_por_curso' => NULL,
                'H' => 6,
                'M' => 1,
                'total' => 7,
            ),
            19 => 
            array (
                'id' => 20,
                'Nombre_del_curso' => 'Operador profesional de excavadora hidráulica',
                'Sector' => 'Industria y construcción',
                'Nombre_del_centro' => 'Centro de capacitación NIMAC',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 56,
                'inicio' => '5/27/2019',
                'fin' => '6/2/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 1917.56,
                'Nombre_del_instructor' => 'Jairo Vega',
                'cupos_por_curso' => NULL,
                'H' => 5,
                'M' => NULL,
                'total' => 5,
            ),
            20 => 
            array (
                'id' => 21,
                'Nombre_del_curso' => 'Mantenimiento preventivo básico maquinaria pesada',
                'Sector' => 'Industria y construcción',
                'Nombre_del_centro' => 'Centro de capacitación NIMAC',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 112,
                'inicio' => '10/18/2019',
                'fin' => '2/22/2020',
                'ao' => 2019,
                'costo_por_participante_USD' => 573.49,
                'Nombre_del_instructor' => 'Darling Silva',
                'cupos_por_curso' => NULL,
                'H' => 8,
                'M' => NULL,
                'total' => 8,
            ),
            21 => 
            array (
                'id' => 22,
                'Nombre_del_curso' => 'Operador básico de retroexcavadora cargadora nivel',
                'Sector' => 'Industria y construcción',
                'Nombre_del_centro' => 'Centro de capacitación NIMAC',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 144,
                'inicio' => '',
                'fin' => '',
                'ao' => 2019,
                'costo_por_participante_USD' => 1917.56,
                'Nombre_del_instructor' => 'Harold Murrillo',
                'cupos_por_curso' => NULL,
                'H' => NULL,
                'M' => NULL,
                'total' => 6,
            ),
            22 => 
            array (
                'id' => 23,
                'Nombre_del_curso' => 'Soldadura de estructuras livianas',
                'Sector' => 'Industria y construcción',
                'Nombre_del_centro' => 'Centro Juvenil Don Bosco',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 220,
                'inicio' => '2/25/2019',
                'fin' => '6/28/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => NULL,
                'Nombre_del_instructor' => '',
                'cupos_por_curso' => NULL,
                'H' => 19,
                'M' => 0,
                'total' => 19,
            ),
            23 => 
            array (
                'id' => 24,
                'Nombre_del_curso' => 'Corte de cabello y barbería',
                'Sector' => 'Comercio y servicios',
                'Nombre_del_centro' => 'Centro Juvenil Don Bosco',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 96,
                'inicio' => '3/2/2019',
                'fin' => '6/29/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => NULL,
                'Nombre_del_instructor' => '',
                'cupos_por_curso' => NULL,
                'H' => 14,
                'M' => 3,
                'total' => 17,
            ),
            24 => 
            array (
                'id' => 25,
                'Nombre_del_curso' => 'Panadería y bollería',
                'Sector' => 'Agroindustria',
                'Nombre_del_centro' => 'Centro Juvenil Don Bosco',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 220,
                'inicio' => '3/4/2019',
                'fin' => '6/28/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => NULL,
                'Nombre_del_instructor' => '',
                'cupos_por_curso' => NULL,
                'H' => 10,
                'M' => 7,
                'total' => 17,
            ),
            25 => 
            array (
                'id' => 26,
                'Nombre_del_curso' => 'Reparación y mantenimiento de motocicleta',
                'Sector' => 'Automotriz',
                'Nombre_del_centro' => 'Centro Juvenil Don Bosco',
                'municipio' => 'Managua ',
                'depto' => 'Managua',
                'carga_horaria' => 240,
                'inicio' => '7/8/2019',
                'fin' => '11/20/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 167.27,
                'Nombre_del_instructor' => 'Santos Antonio Umaña Urrutia',
                'cupos_por_curso' => NULL,
                'H' => NULL,
                'M' => 20,
                'total' => 20,
            ),
            26 => 
            array (
                'id' => 27,
                'Nombre_del_curso' => 'Reparación y mantenimiento de motocicleta',
                'Sector' => 'Automotriz',
                'Nombre_del_centro' => 'Centro Juvenil Don Bosco',
                'municipio' => 'Managua ',
                'depto' => 'Managua',
                'carga_horaria' => 240,
                'inicio' => '7/8/2019',
                'fin' => '11/20/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 167.27,
                'Nombre_del_instructor' => 'Sergio Domingo Andino Rivas',
                'cupos_por_curso' => NULL,
                'H' => NULL,
                'M' => 20,
                'total' => 20,
            ),
            27 => 
            array (
                'id' => 28,
                'Nombre_del_curso' => 'Torno',
                'Sector' => 'Industria y construcción',
                'Nombre_del_centro' => 'Centro Juvenil Don Bosco',
                'municipio' => 'Managua ',
                'depto' => 'Managua',
                'carga_horaria' => 300,
                'inicio' => '8/7/2019',
                'fin' => '11/27/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 217.73,
                'Nombre_del_instructor' => 'Fernando Daniel Carrillo Gutiérrez',
                'cupos_por_curso' => NULL,
                'H' => 14,
                'M' => NULL,
                'total' => 14,
            ),
            28 => 
            array (
                'id' => 29,
                'Nombre_del_curso' => 'Corte de cabello y barbería',
                'Sector' => 'Comercio y servicios',
                'Nombre_del_centro' => 'Centro Juvenil Don Bosco',
                'municipio' => 'Managua ',
                'depto' => 'Managua',
                'carga_horaria' => 90,
                'inicio' => '8/20/2019',
                'fin' => '12/12/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 89.5,
                'Nombre_del_instructor' => 'Meyling Gioconda Hernández Silva',
                'cupos_por_curso' => NULL,
                'H' => 8,
                'M' => 14,
                'total' => 22,
            ),
            29 => 
            array (
                'id' => 30,
                'Nombre_del_curso' => 'Panadería y bollería',
                'Sector' => 'Agroindustria',
                'Nombre_del_centro' => 'Centro Juvenil Don Bosco',
                'municipio' => 'Managua ',
                'depto' => 'Managua',
                'carga_horaria' => 266,
                'inicio' => '8/22/2019',
                'fin' => '12/16/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 217.73,
                'Nombre_del_instructor' => 'Martha Verónica Tellez',
                'cupos_por_curso' => NULL,
                'H' => 5,
                'M' => 5,
                'total' => 10,
            ),
            30 => 
            array (
                'id' => 31,
                'Nombre_del_curso' => 'Reparación de sistema de suspensión y dirección',
                'Sector' => 'Automotriz',
                'Nombre_del_centro' => 'CET Vocacional',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 190,
                'inicio' => '6/3/2019',
                'fin' => '8/9/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 190.0,
                'Nombre_del_instructor' => 'Jose Mariano Rayo',
                'cupos_por_curso' => NULL,
                'H' => 15,
                'M' => NULL,
                'total' => 15,
            ),
            31 => 
            array (
                'id' => 32,
                'Nombre_del_curso' => 'Reparación de sistema de suspensión y dirección',
                'Sector' => 'Automotriz',
                'Nombre_del_centro' => 'CET Vocacional',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 190,
                'inicio' => '6/3/2019',
                'fin' => '8/9/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 190.0,
                'Nombre_del_instructor' => 'Jose Mariano Rayo',
                'cupos_por_curso' => NULL,
                'H' => 14,
                'M' => 3,
                'total' => 17,
            ),
            32 => 
            array (
                'id' => 33,
                'Nombre_del_curso' => 'Mantenimiento y reparación de sistemas de mandos',
                'Sector' => 'Automotriz',
                'Nombre_del_centro' => 'CET Vocacional',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 232,
                'inicio' => '9/18/2019',
                'fin' => '11/20/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 232.0,
                'Nombre_del_instructor' => 'Ronald Navarrete',
                'cupos_por_curso' => NULL,
                'H' => 20,
                'M' => 0,
                'total' => 20,
            ),
            33 => 
            array (
                'id' => 34,
                'Nombre_del_curso' => 'Mantenimiento y reparación de sistemas de mandos',
                'Sector' => 'Automotriz',
                'Nombre_del_centro' => 'CET Vocacional',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 232,
                'inicio' => '9/18/2019',
                'fin' => '11/20/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 232.0,
                'Nombre_del_instructor' => 'Ronald Navarrete',
                'cupos_por_curso' => NULL,
                'H' => 14,
                'M' => NULL,
                'total' => 14,
            ),
            34 => 
            array (
                'id' => 35,
                'Nombre_del_curso' => 'Mantenimiento y reparación de sistemas de mandos',
                'Sector' => 'Automotriz',
                'Nombre_del_centro' => 'CET Vocacional',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 232,
                'inicio' => '9/7/2019',
                'fin' => '1/18/2020',
                'ao' => 2019,
                'costo_por_participante_USD' => 232.0,
                'Nombre_del_instructor' => 'Jairo Sanchez',
                'cupos_por_curso' => NULL,
                'H' => 22,
                'M' => 0,
                'total' => 22,
            ),
            35 => 
            array (
                'id' => 36,
                'Nombre_del_curso' => 'Operaciones auxiliares de recepción y arreglo de habitaciones',
                'Sector' => 'Alojamiento',
                'Nombre_del_centro' => 'Colegio Roberto Clemente Fe y Alegría',
                'municipio' => 'Ciudad Sandino',
                'depto' => 'Managua',
                'carga_horaria' => 192,
                'inicio' => '9/2/2019',
                'fin' => '11/8/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 115.66,
                'Nombre_del_instructor' => '',
                'cupos_por_curso' => NULL,
                'H' => NULL,
                'M' => NULL,
                'total' => 0,
            ),
            36 => 
            array (
                'id' => 37,
                'Nombre_del_curso' => 'Cocina básica',
                'Sector' => 'Gastronomía',
                'Nombre_del_centro' => 'Colegio Roberto Clemente Fe y Alegría',
                'municipio' => 'Ciudad Sandino',
                'depto' => 'Managua',
                'carga_horaria' => 162,
                'inicio' => '9/2/2019',
                'fin' => '10/25/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 168.69,
                'Nombre_del_instructor' => '',
                'cupos_por_curso' => NULL,
                'H' => NULL,
                'M' => NULL,
                'total' => 0,
            ),
            37 => 
            array (
                'id' => 38,
                'Nombre_del_curso' => 'Servicios de bar y restaurante',
                'Sector' => 'Gastronomía',
                'Nombre_del_centro' => 'Colegio Roberto Clemente Fe y Alegría',
                'municipio' => 'Ciudad Sandino',
                'depto' => 'Managua',
                'carga_horaria' => 232,
                'inicio' => '9/2/2019',
                'fin' => '11/8/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 156.81,
                'Nombre_del_instructor' => '',
                'cupos_por_curso' => NULL,
                'H' => NULL,
                'M' => NULL,
                'total' => 0,
            ),
            38 => 
            array (
                'id' => 39,
                'Nombre_del_curso' => 'Electricidad residencial',
                'Sector' => 'Industria y construcción',
                'Nombre_del_centro' => 'Colegio Roberto Clemente Fe y Alegría',
                'municipio' => 'Ciudad Sandino',
                'depto' => 'Managua',
                'carga_horaria' => 190,
                'inicio' => '3/4/2019',
                'fin' => '6/1/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => NULL,
                'Nombre_del_instructor' => '',
                'cupos_por_curso' => NULL,
                'H' => 17,
                'M' => 2,
                'total' => 19,
            ),
            39 => 
            array (
                'id' => 40,
                'Nombre_del_curso' => 'Electricidad automotriz',
                'Sector' => 'Automotriz',
                'Nombre_del_centro' => 'Colegio Roberto Clemente Fe y Alegría',
                'municipio' => 'Ciudad Sandino',
                'depto' => 'Managua',
                'carga_horaria' => 280,
                'inicio' => '3/5/2019',
                'fin' => '6/29/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => NULL,
                'Nombre_del_instructor' => '',
                'cupos_por_curso' => NULL,
                'H' => 21,
                'M' => 1,
                'total' => 22,
            ),
            40 => 
            array (
                'id' => 41,
                'Nombre_del_curso' => 'Reparación de motores de combustión interna',
                'Sector' => 'Automotriz',
                'Nombre_del_centro' => 'Colegio Roberto Clemente Fe y Alegría',
                'municipio' => 'Ciudad Sandino',
                'depto' => 'Managua',
                'carga_horaria' => 188,
                'inicio' => '3/5/2019',
                'fin' => '6/22/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => NULL,
                'Nombre_del_instructor' => '',
                'cupos_por_curso' => NULL,
                'H' => 15,
                'M' => 2,
                'total' => 17,
            ),
            41 => 
            array (
                'id' => 42,
                'Nombre_del_curso' => 'Electricidad automotriz',
                'Sector' => 'Automotriz',
                'Nombre_del_centro' => 'Colegio Roberto Clemente Fe y Alegría',
                'municipio' => 'Ciudad Sandino',
                'depto' => 'Managua',
                'carga_horaria' => 342,
                'inicio' => '10/21/2019',
                'fin' => '2/4/2020',
                'ao' => 2019,
                'costo_por_participante_USD' => 150.0,
                'Nombre_del_instructor' => 'Edison Josué Flores Zamora',
                'cupos_por_curso' => NULL,
                'H' => NULL,
                'M' => NULL,
                'total' => 0,
            ),
            42 => 
            array (
                'id' => 43,
                'Nombre_del_curso' => 'Reparación de motores de combustión interna',
                'Sector' => 'Automotriz',
                'Nombre_del_centro' => 'Colegio Roberto Clemente Fe y Alegría',
                'municipio' => 'Ciudad Sandino',
                'depto' => 'Managua',
                'carga_horaria' => 218,
                'inicio' => '10/23/2019',
                'fin' => '2/4/2020',
                'ao' => 2019,
                'costo_por_participante_USD' => 112.06,
                'Nombre_del_instructor' => 'Johnatan Perez',
                'cupos_por_curso' => NULL,
                'H' => NULL,
                'M' => NULL,
                'total' => 0,
            ),
            43 => 
            array (
                'id' => 44,
                'Nombre_del_curso' => 'Soldadura estructura liviana',
                'Sector' => 'Industria y construcción',
                'Nombre_del_centro' => 'Colegio Roberto Clemente Fe y Alegría',
                'municipio' => 'Ciudad Sandino',
                'depto' => 'Managua',
                'carga_horaria' => 230,
                'inicio' => '10/25/2019',
                'fin' => '2/4/2020',
                'ao' => 2019,
                'costo_por_participante_USD' => 164.05,
                'Nombre_del_instructor' => 'Lesther Deibi Escoto',
                'cupos_por_curso' => NULL,
                'H' => NULL,
                'M' => NULL,
                'total' => 0,
            ),
            44 => 
            array (
                'id' => 45,
                'Nombre_del_curso' => 'Reparación y mantenimiento de motocicleta',
                'Sector' => 'Automotriz',
                'Nombre_del_centro' => 'Fundación Samuel',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 228,
                'inicio' => '9/26/2019',
                'fin' => '12/9/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 171.44,
                'Nombre_del_instructor' => 'Julio Velásquez_x000D_ Calixta Zamora_x000D_ Ernestina Mejía_x000D_ ',
                'cupos_por_curso' => NULL,
                'H' => 20,
                'M' => NULL,
                'total' => 20,
            ),
            45 => 
            array (
                'id' => 46,
                'Nombre_del_curso' => 'Asistente de tienda de conveniencia',
                'Sector' => 'Comercio y servicios',
                'Nombre_del_centro' => 'Fundación Victoria',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 160,
                'inicio' => '6/10/2019',
                'fin' => '7/5/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 112.93,
                'Nombre_del_instructor' => 'Octavio Arana',
                'cupos_por_curso' => NULL,
                'H' => 7,
                'M' => 12,
                'total' => 19,
            ),
            46 => 
            array (
                'id' => 47,
                'Nombre_del_curso' => 'Encargado de tienda de conveniencia',
                'Sector' => 'Comercio y servicios',
                'Nombre_del_centro' => 'Fundación Victoria',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 168,
                'inicio' => '7/8/2019',
                'fin' => '8/9/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 112.93,
                'Nombre_del_instructor' => 'Eliú Aragón',
                'cupos_por_curso' => NULL,
                'H' => 10,
                'M' => 10,
                'total' => 20,
            ),
            47 => 
            array (
                'id' => 48,
                'Nombre_del_curso' => 'Asistente de tienda de conveniencia',
                'Sector' => 'Comercio y servicios',
                'Nombre_del_centro' => 'Fundación Victoria',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 160,
                'inicio' => '8/12/2019',
                'fin' => '9/6/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 112.93,
                'Nombre_del_instructor' => 'Luis Adolfo González',
                'cupos_por_curso' => NULL,
                'H' => 2,
                'M' => 13,
                'total' => 15,
            ),
            48 => 
            array (
                'id' => 49,
                'Nombre_del_curso' => 'Encargado de tienda de conveniencia',
                'Sector' => 'Comercio y servicios',
                'Nombre_del_centro' => 'Fundación Victoria',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 168,
                'inicio' => '9/2/2019',
                'fin' => '10/4/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 112.93,
                'Nombre_del_instructor' => 'Octavio Arana',
                'cupos_por_curso' => NULL,
                'H' => 7,
                'M' => 13,
                'total' => 20,
            ),
            49 => 
            array (
                'id' => 50,
                'Nombre_del_curso' => 'Elaboración de conservas y derivados lácteos',
                'Sector' => 'Agroindustria',
                'Nombre_del_centro' => 'Fundación Victoria',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 172,
                'inicio' => '9/9/2019',
                'fin' => '11/29/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 153.12,
                'Nombre_del_instructor' => 'Marvin Hernández;',
                'cupos_por_curso' => NULL,
                'H' => 0,
                'M' => 16,
                'total' => 16,
            ),
            50 => 
            array (
                'id' => 51,
                'Nombre_del_curso' => 'Asistente de tienda de conveniencia',
                'Sector' => 'Comercio y servicios',
                'Nombre_del_centro' => 'Fundación Victoria',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 160,
                'inicio' => '10/7/2019',
                'fin' => '11/1/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 112.93,
                'Nombre_del_instructor' => 'Jorge Romero',
                'cupos_por_curso' => NULL,
                'H' => 11,
                'M' => 5,
                'total' => 16,
            ),
            51 => 
            array (
                'id' => 52,
                'Nombre_del_curso' => 'Encargado de tienda de conveniencia',
                'Sector' => 'Comercio y servicios',
                'Nombre_del_centro' => 'Fundación Victoria',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 168,
                'inicio' => '11/11/2019',
                'fin' => '12/9/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 112.93,
                'Nombre_del_instructor' => 'Erika Dávila',
                'cupos_por_curso' => NULL,
                'H' => 7,
                'M' => 10,
                'total' => 17,
            ),
            52 => 
            array (
                'id' => 53,
                'Nombre_del_curso' => 'Cocina básica',
                'Sector' => 'Gastronomía',
                'Nombre_del_centro' => 'Hogar Zacarías Guerra',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 180,
                'inicio' => '3/18/2019',
                'fin' => '5/18/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => NULL,
                'Nombre_del_instructor' => '',
                'cupos_por_curso' => NULL,
                'H' => 6,
                'M' => 14,
                'total' => 20,
            ),
            53 => 
            array (
                'id' => 54,
                'Nombre_del_curso' => 'Corte y confección',
                'Sector' => 'Textil-Vestuario',
                'Nombre_del_centro' => 'Hogar Zacarías Guerra',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 230,
                'inicio' => '3/18/2019',
                'fin' => '5/18/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => NULL,
                'Nombre_del_instructor' => '',
                'cupos_por_curso' => NULL,
                'H' => 3,
                'M' => 18,
                'total' => 21,
            ),
            54 => 
            array (
                'id' => 55,
                'Nombre_del_curso' => 'Cocina básica',
                'Sector' => 'Gastronomía',
                'Nombre_del_centro' => 'Hogar Zacarías Guerra',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 252,
                'inicio' => '10/1/2019',
                'fin' => '12/10/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 233.0,
                'Nombre_del_instructor' => 'Brigitte Godoy',
                'cupos_por_curso' => NULL,
                'H' => 11,
                'M' => 9,
                'total' => 20,
            ),
            55 => 
            array (
                'id' => 56,
                'Nombre_del_curso' => 'Cocina básica',
                'Sector' => 'Gastronomía',
                'Nombre_del_centro' => 'Hogar Zacarías Guerra',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 252,
                'inicio' => '10/1/2019',
                'fin' => '12/10/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 233.0,
                'Nombre_del_instructor' => 'Marcio Munguia Pavon',
                'cupos_por_curso' => NULL,
                'H' => 5,
                'M' => 15,
                'total' => 20,
            ),
            56 => 
            array (
                'id' => 57,
                'Nombre_del_curso' => 'Corte y confección',
                'Sector' => 'Textil-Vestuario',
                'Nombre_del_centro' => 'Hogar Zacarías Guerra',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 212,
                'inicio' => '10/1/2019',
                'fin' => '12/10/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 210.0,
                'Nombre_del_instructor' => 'Tamara Sequeira',
                'cupos_por_curso' => NULL,
                'H' => 4,
                'M' => 13,
                'total' => 17,
            ),
            57 => 
            array (
                'id' => 58,
                'Nombre_del_curso' => 'Reparación y mantenimiento de motocicleta',
                'Sector' => 'Automotriz',
                'Nombre_del_centro' => 'Hogar Zacarías Guerra',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 256,
                'inicio' => '10/1/2019',
                'fin' => '12/10/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 282.0,
                'Nombre_del_instructor' => 'Santos Antonio Umaña',
                'cupos_por_curso' => NULL,
                'H' => 18,
                'M' => 2,
                'total' => 20,
            ),
            58 => 
            array (
                'id' => 59,
                'Nombre_del_curso' => 'Reparación y mantenimiento de motocicleta',
                'Sector' => 'Automotriz',
                'Nombre_del_centro' => 'Hogar Zacarías Guerra',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 256,
                'inicio' => '10/1/2019',
                'fin' => '12/10/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 282.0,
                'Nombre_del_instructor' => 'Santos Antonio Umaña',
                'cupos_por_curso' => NULL,
                'H' => 20,
                'M' => NULL,
                'total' => 20,
            ),
            59 => 
            array (
                'id' => 60,
                'Nombre_del_curso' => 'Técnicas de servicio al huésped',
                'Sector' => 'Alojamiento',
                'Nombre_del_centro' => 'Hogar Zacarías Guerra',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 132,
                'inicio' => '10/1/2019',
                'fin' => '12/10/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 181.4,
                'Nombre_del_instructor' => 'Arlen Orozco',
                'cupos_por_curso' => NULL,
                'H' => 7,
                'M' => 11,
                'total' => 18,
            ),
            60 => 
            array (
                'id' => 61,
                'Nombre_del_curso' => 'Apicultura y diversificación de fincas',
                'Sector' => 'Agroindustria',
                'Nombre_del_centro' => 'INPRHU',
                'municipio' => 'Las Sabanas',
                'depto' => 'Madriz',
                'carga_horaria' => 120,
                'inicio' => '6/4/2019',
                'fin' => '9/23/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 120.0,
                'Nombre_del_instructor' => 'Aarón Vásquez Blandón',
                'cupos_por_curso' => NULL,
                'H' => NULL,
                'M' => 13,
                'total' => 13,
            ),
            61 => 
            array (
                'id' => 62,
                'Nombre_del_curso' => 'Apicultura y diversificación de fincas',
                'Sector' => 'Agroindustria',
                'Nombre_del_centro' => 'INPRHU',
                'municipio' => 'San Lucas',
                'depto' => 'Madriz',
                'carga_horaria' => 120,
                'inicio' => '6/3/2019',
                'fin' => '9/24/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 120.0,
                'Nombre_del_instructor' => 'Rolando Bertrand',
                'cupos_por_curso' => NULL,
                'H' => NULL,
                'M' => 13,
                'total' => 13,
            ),
            62 => 
            array (
                'id' => 63,
                'Nombre_del_curso' => 'Apicultura y diversificación de fincas',
                'Sector' => 'Agroindustria',
                'Nombre_del_centro' => 'INPRHU',
                'municipio' => 'Somoto',
                'depto' => 'Madriz',
                'carga_horaria' => 120,
                'inicio' => '6/6/2019',
                'fin' => '9/26/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 120.0,
                'Nombre_del_instructor' => 'María Cristina Lanuza',
                'cupos_por_curso' => NULL,
                'H' => NULL,
                'M' => 24,
                'total' => 24,
            ),
            63 => 
            array (
                'id' => 64,
                'Nombre_del_curso' => 'Apicultura y diversificación de fincas',
                'Sector' => 'Agroindustria',
                'Nombre_del_centro' => 'INPRHU',
                'municipio' => 'Totogalpa',
                'depto' => 'Madriz',
                'carga_horaria' => 120,
                'inicio' => '6/3/2019',
                'fin' => '9/30/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 120.0,
                'Nombre_del_instructor' => 'María Cristina Lanuza',
                'cupos_por_curso' => NULL,
                'H' => NULL,
                'M' => 22,
                'total' => 22,
            ),
            64 => 
            array (
                'id' => 65,
                'Nombre_del_curso' => 'Procesamiento artesanal de frutas, vegetales y dulces',
                'Sector' => 'Agroindustria',
                'Nombre_del_centro' => 'INPRHU',
                'municipio' => 'Las Sabanas',
                'depto' => 'Madriz',
                'carga_horaria' => 120,
                'inicio' => '6/3/2019',
                'fin' => '9/25/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 120.0,
                'Nombre_del_instructor' => 'María Cristina Lanuza',
                'cupos_por_curso' => NULL,
                'H' => NULL,
                'M' => 23,
                'total' => 23,
            ),
            65 => 
            array (
                'id' => 66,
                'Nombre_del_curso' => 'Procesamiento artesanal de frutas, vegetales y dulces',
                'Sector' => 'Agroindustria',
                'Nombre_del_centro' => 'INPRHU',
                'municipio' => 'Las Sabanas',
                'depto' => 'Madriz',
                'carga_horaria' => 120,
                'inicio' => '6/6/2019',
                'fin' => '9/23/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 120.0,
                'Nombre_del_instructor' => 'María Cristina Lanuza',
                'cupos_por_curso' => NULL,
                'H' => NULL,
                'M' => 22,
                'total' => 22,
            ),
            66 => 
            array (
                'id' => 67,
                'Nombre_del_curso' => 'Procesamiento artesanal de frutas, vegetales y dulces',
                'Sector' => 'Agroindustria',
                'Nombre_del_centro' => 'INPRHU',
                'municipio' => 'San Lucas',
                'depto' => 'Madriz',
                'carga_horaria' => 120,
                'inicio' => '6/6/2019',
                'fin' => '9/29/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 120.0,
                'Nombre_del_instructor' => 'Uriel Montoya Betanco',
                'cupos_por_curso' => NULL,
                'H' => NULL,
                'M' => 18,
                'total' => 18,
            ),
            67 => 
            array (
                'id' => 68,
                'Nombre_del_curso' => 'Procesamiento artesanal de frutas, vegetales y dulces',
                'Sector' => 'Agroindustria',
                'Nombre_del_centro' => 'INPRHU',
                'municipio' => 'San Lucas',
                'depto' => 'Madriz',
                'carga_horaria' => 120,
                'inicio' => '6/3/2019',
                'fin' => '9/23/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 120.0,
                'Nombre_del_instructor' => 'Uriel Montoya',
                'cupos_por_curso' => NULL,
                'H' => NULL,
                'M' => 17,
                'total' => 17,
            ),
            68 => 
            array (
                'id' => 69,
                'Nombre_del_curso' => 'Procesamiento artesanal de frutas, vegetales y dulces',
                'Sector' => 'Agroindustria',
                'Nombre_del_centro' => 'INPRHU',
                'municipio' => 'Yalagüina',
                'depto' => 'Madriz',
                'carga_horaria' => 120,
                'inicio' => '6/4/2019',
                'fin' => '9/26/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 120.0,
                'Nombre_del_instructor' => 'Jeysson Gutiérrez',
                'cupos_por_curso' => NULL,
                'H' => 5,
                'M' => 15,
                'total' => 20,
            ),
            69 => 
            array (
                'id' => 70,
                'Nombre_del_curso' => 'Procesamiento artesanal de frutas, vegetales y dulces',
                'Sector' => 'Agroindustria',
                'Nombre_del_centro' => 'INPRHU',
                'municipio' => 'Yalagüina',
                'depto' => 'Madriz',
                'carga_horaria' => 120,
                'inicio' => '6/3/2019',
                'fin' => '9/23/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 120.0,
                'Nombre_del_instructor' => 'Jeysson Gutiérrez',
                'cupos_por_curso' => NULL,
                'H' => 5,
                'M' => 14,
                'total' => 19,
            ),
            70 => 
            array (
                'id' => 71,
                'Nombre_del_curso' => 'Electricidad automotriz',
                'Sector' => 'Automotriz',
                'Nombre_del_centro' => 'Instituto Politécnico La Salle',
                'municipio' => 'León',
                'depto' => 'León',
                'carga_horaria' => 116,
                'inicio' => '4/6/2019',
                'fin' => '7/20/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => NULL,
                'Nombre_del_instructor' => '',
                'cupos_por_curso' => NULL,
                'H' => 18,
                'M' => 1,
                'total' => 19,
            ),
            71 => 
            array (
                'id' => 72,
                'Nombre_del_curso' => 'Electricidad residencial',
                'Sector' => 'Industria y construcción',
                'Nombre_del_centro' => 'Instituto Politécnico La Salle',
                'municipio' => 'León',
                'depto' => 'León',
                'carga_horaria' => 116,
                'inicio' => '4/6/2019',
                'fin' => '7/20/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => NULL,
                'Nombre_del_instructor' => '',
                'cupos_por_curso' => NULL,
                'H' => 15,
                'M' => 2,
                'total' => 17,
            ),
            72 => 
            array (
                'id' => 73,
                'Nombre_del_curso' => 'Mecánica básica automotriz',
                'Sector' => 'Automotriz',
                'Nombre_del_centro' => 'Instituto Politécnico La Salle',
                'municipio' => 'León',
                'depto' => 'León',
                'carga_horaria' => 116,
                'inicio' => '4/6/2019',
                'fin' => '7/20/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => NULL,
                'Nombre_del_instructor' => '',
                'cupos_por_curso' => NULL,
                'H' => 19,
                'M' => 1,
                'total' => 20,
            ),
            73 => 
            array (
                'id' => 74,
                'Nombre_del_curso' => 'Soldadura básica eléctrica y autógena',
                'Sector' => 'Industria y construcción',
                'Nombre_del_centro' => 'Instituto Politécnico La Salle',
                'municipio' => 'León',
                'depto' => 'León',
                'carga_horaria' => 116,
                'inicio' => '4/6/2019',
                'fin' => '7/20/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => NULL,
                'Nombre_del_instructor' => '',
                'cupos_por_curso' => NULL,
                'H' => 19,
                'M' => 4,
                'total' => 23,
            ),
            74 => 
            array (
                'id' => 75,
                'Nombre_del_curso' => 'Mantenimiento equipos línea marrón',
                'Sector' => 'Comercio y servicios',
                'Nombre_del_centro' => 'Instituto Politécnico La Salle',
                'municipio' => 'León',
                'depto' => 'León',
                'carga_horaria' => 262,
                'inicio' => '5/5/2019',
                'fin' => '9/8/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 195.59,
                'Nombre_del_instructor' => 'Armando Coulson',
                'cupos_por_curso' => NULL,
                'H' => 17,
                'M' => 1,
                'total' => 18,
            ),
            75 => 
            array (
                'id' => 76,
                'Nombre_del_curso' => 'Climatización automotriz',
                'Sector' => 'Automotriz',
                'Nombre_del_centro' => 'Instituto Politécnico La Salle',
                'municipio' => 'Leon',
                'depto' => 'León',
                'carga_horaria' => 116,
                'inicio' => '8/10/2019',
                'fin' => '11/23/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 155.04,
                'Nombre_del_instructor' => 'Juan Gabriel Barrera',
                'cupos_por_curso' => NULL,
                'H' => 21,
                'M' => NULL,
                'total' => 21,
            ),
            76 => 
            array (
                'id' => 77,
                'Nombre_del_curso' => 'Mantenimiento electrodomésticos línea gris',
                'Sector' => 'Comercio y servicios',
                'Nombre_del_centro' => 'Instituto Politécnico La Salle',
                'municipio' => 'Leon',
                'depto' => 'León',
                'carga_horaria' => 156,
                'inicio' => '8/11/2019',
                'fin' => '12/1/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 147.8,
                'Nombre_del_instructor' => 'Armando Coulson',
                'cupos_por_curso' => NULL,
                'H' => 15,
                'M' => 1,
                'total' => 16,
            ),
            77 => 
            array (
                'id' => 78,
                'Nombre_del_curso' => 'Reparación de motores de combustión interna',
                'Sector' => 'Automotriz',
                'Nombre_del_centro' => 'Instituto Politécnico La Salle',
                'municipio' => 'Leon',
                'depto' => 'León',
                'carga_horaria' => 186,
                'inicio' => '8/10/2019',
                'fin' => '11/30/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 154.77,
                'Nombre_del_instructor' => 'Salvador Gonzales/Francisco Iglesiias',
                'cupos_por_curso' => NULL,
                'H' => 22,
                'M' => NULL,
                'total' => 22,
            ),
            78 => 
            array (
                'id' => 79,
                'Nombre_del_curso' => 'Tornero básico',
                'Sector' => 'Industria y construcción',
                'Nombre_del_centro' => 'Instituto Politécnico La Salle',
                'municipio' => 'Leon',
                'depto' => 'León',
                'carga_horaria' => 140,
                'inicio' => '8/11/2019',
                'fin' => '12/1/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 152.77,
                'Nombre_del_instructor' => 'Juan Agustin Murillo',
                'cupos_por_curso' => NULL,
                'H' => 18,
                'M' => 1,
                'total' => 19,
            ),
            79 => 
            array (
                'id' => 80,
                'Nombre_del_curso' => 'Control y arranque de motores trifásicos',
                'Sector' => 'Industria y construcción',
                'Nombre_del_centro' => 'Instituto Politécnico La Salle',
                'municipio' => 'León',
                'depto' => 'León',
                'carga_horaria' => 156,
                'inicio' => '8/10/2019',
                'fin' => '11/30/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 155.0,
                'Nombre_del_instructor' => 'Francisco Barcenas',
                'cupos_por_curso' => NULL,
                'H' => 21,
                'M' => 0,
                'total' => 21,
            ),
            80 => 
            array (
                'id' => 81,
                'Nombre_del_curso' => 'Reparación y mantenimiento de motocicleta',
                'Sector' => 'Automotriz',
                'Nombre_del_centro' => 'Instituto Politécnico La Salle',
                'municipio' => 'León',
                'depto' => 'León',
                'carga_horaria' => 266,
                'inicio' => '11/4/2019',
                'fin' => '1/31/2020',
                'ao' => 2019,
                'costo_por_participante_USD' => 186.26,
                'Nombre_del_instructor' => 'Juan Gabriel Barrera',
                'cupos_por_curso' => NULL,
                'H' => 16,
                'M' => 1,
                'total' => 17,
            ),
            81 => 
            array (
                'id' => 82,
                'Nombre_del_curso' => 'Soldadura especializada MIG y TIC',
                'Sector' => 'Industria y construcción',
                'Nombre_del_centro' => 'Instituto Politécnico La Salle',
                'municipio' => 'León',
                'depto' => 'León',
                'carga_horaria' => 116,
                'inicio' => '8/10/2019',
                'fin' => '11/23/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 172.44,
                'Nombre_del_instructor' => 'William Lopez',
                'cupos_por_curso' => NULL,
                'H' => 22,
                'M' => NULL,
                'total' => 22,
            ),
            82 => 
            array (
                'id' => 83,
                'Nombre_del_curso' => 'Cocina nicaragüense',
                'Sector' => 'Gastronomía',
                'Nombre_del_centro' => 'JA Nicaragua',
                'municipio' => 'San Rafael del Sur',
                'depto' => 'Managua',
                'carga_horaria' => 100,
                'inicio' => '4/23/2019',
                'fin' => '6/14/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => NULL,
                'Nombre_del_instructor' => '',
                'cupos_por_curso' => NULL,
                'H' => NULL,
                'M' => 23,
                'total' => 23,
            ),
            83 => 
            array (
                'id' => 84,
                'Nombre_del_curso' => 'Cocina nicaragüense',
                'Sector' => 'Gastronomía',
                'Nombre_del_centro' => 'JA Nicaragua',
                'municipio' => 'San Rafael del Sur',
                'depto' => 'Managua',
                'carga_horaria' => 100,
                'inicio' => '4/23/2019',
                'fin' => '6/14/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => NULL,
                'Nombre_del_instructor' => '',
                'cupos_por_curso' => NULL,
                'H' => 3,
                'M' => 18,
                'total' => 21,
            ),
            84 => 
            array (
                'id' => 85,
                'Nombre_del_curso' => 'Corte y confección prendas para dama',
                'Sector' => 'Textil-Vestuario',
                'Nombre_del_centro' => 'JA Nicaragua',
                'municipio' => 'San Rafael del Sur',
                'depto' => 'Managua',
                'carga_horaria' => 150,
                'inicio' => '4/23/2019',
                'fin' => '6/2/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => NULL,
                'Nombre_del_instructor' => '',
                'cupos_por_curso' => NULL,
                'H' => NULL,
                'M' => 21,
                'total' => 21,
            ),
            85 => 
            array (
                'id' => 86,
                'Nombre_del_curso' => 'Corte y confección prendas para dama',
                'Sector' => 'Textil-Vestuario',
                'Nombre_del_centro' => 'JA Nicaragua',
                'municipio' => 'San Rafael del Sur',
                'depto' => 'Managua',
                'carga_horaria' => 150,
                'inicio' => '4/23/2019',
                'fin' => '6/2/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => NULL,
                'Nombre_del_instructor' => '',
                'cupos_por_curso' => NULL,
                'H' => 1,
                'M' => 20,
                'total' => 21,
            ),
            86 => 
            array (
                'id' => 87,
                'Nombre_del_curso' => 'Reparación y mantenimiento de motocicleta',
                'Sector' => 'Automotriz',
                'Nombre_del_centro' => 'Instituto Politécnico La Salle',
                'municipio' => 'León',
                'depto' => 'León',
                'carga_horaria' => 266,
                'inicio' => '9/23/2019',
                'fin' => '12/6/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 186.26,
                'Nombre_del_instructor' => 'Juan Gabriel Barrera',
                'cupos_por_curso' => NULL,
                'H' => 19,
                'M' => NULL,
                'total' => 19,
            ),
            87 => 
            array (
                'id' => 88,
                'Nombre_del_curso' => 'Corte y confección',
                'Sector' => 'Textil-Vestuario',
                'Nombre_del_centro' => 'Kolping',
                'municipio' => 'Managua ',
                'depto' => 'Managua',
                'carga_horaria' => 156,
                'inicio' => '8/9/2019',
                'fin' => '12/28/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 233.85,
                'Nombre_del_instructor' => 'Marttha Esmeralda Pérez Quintanilla',
                'cupos_por_curso' => NULL,
                'H' => 1,
                'M' => 16,
                'total' => 17,
            ),
            88 => 
            array (
                'id' => 89,
                'Nombre_del_curso' => 'Electrónica básica',
                'Sector' => 'Industria y construcción',
                'Nombre_del_centro' => 'Kolping',
                'municipio' => 'Managua ',
                'depto' => 'Managua',
                'carga_horaria' => 204,
                'inicio' => '8/9/2019',
                'fin' => '2/15/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 238.58,
                'Nombre_del_instructor' => 'Ronald de Jesús Morales Paladino',
                'cupos_por_curso' => NULL,
                'H' => 4,
                'M' => NULL,
                'total' => 4,
            ),
            89 => 
            array (
                'id' => 90,
                'Nombre_del_curso' => 'Corte y confección',
                'Sector' => 'Textil-Vestuario',
                'Nombre_del_centro' => 'La Cuculmeca ',
                'municipio' => 'Jinotega',
                'depto' => 'Jinotega',
                'carga_horaria' => 100,
                'inicio' => '6/20/2019',
                'fin' => '9/5/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 157.8,
                'Nombre_del_instructor' => 'Yulieth Herrera Castro',
                'cupos_por_curso' => NULL,
                'H' => 1,
                'M' => 13,
                'total' => 14,
            ),
            90 => 
            array (
                'id' => 91,
                'Nombre_del_curso' => 'Electricidad residencial',
                'Sector' => 'Industria y construcción',
                'Nombre_del_centro' => 'La Cuculmeca ',
                'municipio' => 'Jinotega',
                'depto' => 'Jinotega',
                'carga_horaria' => 100,
                'inicio' => '6/20/2019',
                'fin' => '9/5/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 194.25,
                'Nombre_del_instructor' => 'Juan Antonio Silva Palacios',
                'cupos_por_curso' => NULL,
                'H' => 16,
                'M' => 2,
                'total' => 18,
            ),
            91 => 
            array (
                'id' => 92,
                'Nombre_del_curso' => 'Reparación y mantenimiento de computadoras',
                'Sector' => 'Comercio y servicios',
                'Nombre_del_centro' => 'La Cuculmeca ',
                'municipio' => 'Jinotega',
                'depto' => 'Jinotega',
                'carga_horaria' => 100,
                'inicio' => '6/20/2019',
                'fin' => '9/5/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 178.68,
                'Nombre_del_instructor' => 'Juan Antonio Silva Palacios',
                'cupos_por_curso' => NULL,
                'H' => 7,
                'M' => 9,
                'total' => 16,
            ),
            92 => 
            array (
                'id' => 93,
                'Nombre_del_curso' => 'Elaboración de néctares y conserva',
                'Sector' => 'Agroindustria',
                'Nombre_del_centro' => 'Fundación Fabretto',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 125,
                'inicio' => '3/26/2019',
                'fin' => '8/26/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => NULL,
                'Nombre_del_instructor' => '',
                'cupos_por_curso' => NULL,
                'H' => 18,
                'M' => 8,
                'total' => 26,
            ),
            93 => 
            array (
                'id' => 94,
                'Nombre_del_curso' => 'Apicultura tropical',
                'Sector' => 'Agroindustria',
                'Nombre_del_centro' => 'Fundación Fabretto',
                'municipio' => 'Cusmapa',
                'depto' => 'Madriz',
                'carga_horaria' => 144,
                'inicio' => '3/26/2019',
                'fin' => '7/26/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => NULL,
                'Nombre_del_instructor' => '',
                'cupos_por_curso' => NULL,
                'H' => 12,
                'M' => 7,
                'total' => 19,
            ),
            94 => 
            array (
                'id' => 95,
                'Nombre_del_curso' => 'Apicultura tropical',
                'Sector' => 'Agroindustria',
                'Nombre_del_centro' => 'Fundación Fabretto',
                'municipio' => 'Somoto',
                'depto' => 'Madriz',
                'carga_horaria' => 144,
                'inicio' => '3/26/2019',
                'fin' => '7/26/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => NULL,
                'Nombre_del_instructor' => '',
                'cupos_por_curso' => NULL,
                'H' => 16,
                'M' => 10,
                'total' => 26,
            ),
            95 => 
            array (
                'id' => 96,
                'Nombre_del_curso' => 'Apicultura tropical',
                'Sector' => 'Agroindustria',
                'Nombre_del_centro' => 'Fundación Fabretto',
                'municipio' => 'Jalapa',
                'depto' => 'Nueva Segovia',
                'carga_horaria' => 144,
                'inicio' => '5/9/2019',
                'fin' => '8/29/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => NULL,
                'Nombre_del_instructor' => '',
                'cupos_por_curso' => NULL,
                'H' => 7,
                'M' => 7,
                'total' => 14,
            ),
            96 => 
            array (
                'id' => 97,
                'Nombre_del_curso' => 'Cocina básica',
                'Sector' => 'Gastronomía',
                'Nombre_del_centro' => 'Fundación Fabretto',
                'municipio' => 'Estelí',
                'depto' => 'Estelí',
                'carga_horaria' => 115,
                'inicio' => '10/18/2019',
                'fin' => '1/31/2020',
                'ao' => 2019,
                'costo_por_participante_USD' => 182.25,
                'Nombre_del_instructor' => 'Bosco Roblero Gómez',
                'cupos_por_curso' => NULL,
                'H' => 1,
                'M' => 20,
                'total' => 21,
            ),
            97 => 
            array (
                'id' => 98,
                'Nombre_del_curso' => 'Cocina básica',
                'Sector' => 'Gastronomía',
                'Nombre_del_centro' => 'Fundación Fabretto',
                'municipio' => 'Granada',
                'depto' => 'Granada',
                'carga_horaria' => 115,
                'inicio' => '10/17/2019',
                'fin' => '1/31/2020',
                'ao' => 2019,
                'costo_por_participante_USD' => 182.25,
                'Nombre_del_instructor' => 'Eva Castillo Suarez',
                'cupos_por_curso' => NULL,
                'H' => 1,
                'M' => 22,
                'total' => 23,
            ),
            98 => 
            array (
                'id' => 99,
                'Nombre_del_curso' => 'Producción artesanal de alimentos',
                'Sector' => 'Agroindustria',
                'Nombre_del_centro' => 'Fundación Fabretto',
                'municipio' => 'Somoto',
                'depto' => 'Madriz',
                'carga_horaria' => 118,
                'inicio' => '10/19/2019',
                'fin' => '1/31/2020',
                'ao' => 2019,
                'costo_por_participante_USD' => 190.34,
                'Nombre_del_instructor' => 'Katherine Padilla Alfaro',
                'cupos_por_curso' => NULL,
                'H' => 6,
                'M' => 14,
                'total' => 20,
            ),
            99 => 
            array (
                'id' => 100,
                'Nombre_del_curso' => 'Producción artesanal de alimentos',
                'Sector' => 'Agroindustria',
                'Nombre_del_centro' => 'Fundación Fabretto',
                'municipio' => 'Ocotal',
                'depto' => 'Nueva Segovia',
                'carga_horaria' => 118,
                'inicio' => '10/16/2019',
                'fin' => '1/31/2020',
                'ao' => 2019,
                'costo_por_participante_USD' => 190.34,
                'Nombre_del_instructor' => 'Katherine Padilla Alfaro',
                'cupos_por_curso' => NULL,
                'H' => 5,
                'M' => 18,
                'total' => 23,
            ),
            100 => 
            array (
                'id' => 101,
                'Nombre_del_curso' => 'Apicultura tropical énfasis BPA',
                'Sector' => 'Agroindustria',
                'Nombre_del_centro' => 'PRONAMIEL',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 104,
                'inicio' => '6/11/2019',
                'fin' => '7/31/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 160.86,
                'Nombre_del_instructor' => 'Danilo Roman Plata',
                'cupos_por_curso' => NULL,
                'H' => 17,
                'M' => 9,
                'total' => 26,
            ),
            101 => 
            array (
                'id' => 102,
                'Nombre_del_curso' => 'Apicultura tropical énfasis BPA',
                'Sector' => 'Agroindustria',
                'Nombre_del_centro' => 'PRONAMIEL',
                'municipio' => 'San Francisco Libre',
                'depto' => 'Managua',
                'carga_horaria' => 104,
                'inicio' => '6/12/2019',
                'fin' => '7/24/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 160.86,
                'Nombre_del_instructor' => 'Mario Artola',
                'cupos_por_curso' => NULL,
                'H' => 19,
                'M' => 8,
                'total' => 21,
            ),
            102 => 
            array (
                'id' => 103,
                'Nombre_del_curso' => 'Valor agregado producción de miel y otros productos de la colmena',
                'Sector' => 'Agroindustria',
                'Nombre_del_centro' => 'PRONAMIEL',
                'municipio' => 'San Francisco Libre',
                'depto' => 'Managua',
                'carga_horaria' => 64,
                'inicio' => '6/21/2019',
                'fin' => '7/14/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 144.49,
                'Nombre_del_instructor' => 'Maria Elena Matute',
                'cupos_por_curso' => NULL,
                'H' => 18,
                'M' => 7,
                'total' => 21,
            ),
            103 => 
            array (
                'id' => 104,
                'Nombre_del_curso' => 'Apicultura tropical énfasis BPA',
                'Sector' => 'Agroindustria',
                'Nombre_del_centro' => 'PRONAMIEL',
                'municipio' => 'Quilalí',
                'depto' => 'Nueva Segovia',
                'carga_horaria' => 110,
                'inicio' => '8/28/2019',
                'fin' => '10/10/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 127.54,
                'Nombre_del_instructor' => 'Felix Raudales /Yamileth Guevara',
                'cupos_por_curso' => NULL,
                'H' => 17,
                'M' => 3,
                'total' => 20,
            ),
            104 => 
            array (
                'id' => 105,
                'Nombre_del_curso' => 'Apicultura tropical énfasis BPA',
                'Sector' => 'Agroindustria',
                'Nombre_del_centro' => 'PRONAMIEL',
                'municipio' => 'Jinotega',
                'depto' => 'Jinotega',
                'carga_horaria' => 110,
                'inicio' => '10/10/2019',
                'fin' => '11/22/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 127.54,
                'Nombre_del_instructor' => 'Felix Raudales /Yamileth Guevara',
                'cupos_por_curso' => NULL,
                'H' => 20,
                'M' => 5,
                'total' => 25,
            ),
            105 => 
            array (
                'id' => 106,
                'Nombre_del_curso' => 'Valor agregado producción de miel y otros productos de la colmena',
                'Sector' => 'Agroindustria',
                'Nombre_del_centro' => 'PRONAMIEL',
                'municipio' => 'Jinotega',
                'depto' => 'Jinotega',
                'carga_horaria' => 94,
                'inicio' => '9/30/2019',
                'fin' => '10/21/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 144.97,
                'Nombre_del_instructor' => 'Maria Elena Matute',
                'cupos_por_curso' => NULL,
                'H' => 5,
                'M' => 14,
                'total' => 19,
            ),
            106 => 
            array (
                'id' => 107,
                'Nombre_del_curso' => 'Valor agregado producción de miel y otros productos de la colmena',
                'Sector' => 'Agroindustria',
                'Nombre_del_centro' => 'PRONAMIEL',
                'municipio' => 'Somoto',
                'depto' => 'Madriz',
                'carga_horaria' => 96,
                'inicio' => '9/19/2019',
                'fin' => '10/28/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 144.49,
                'Nombre_del_instructor' => 'Yamileth Guevara',
                'cupos_por_curso' => NULL,
                'H' => 7,
                'M' => 11,
                'total' => 18,
            ),
            107 => 
            array (
                'id' => 108,
                'Nombre_del_curso' => 'Apicultura tropical énfasis BPA',
                'Sector' => 'Agroindustria',
                'Nombre_del_centro' => 'PRONAMIEL',
                'municipio' => 'El Cuá-Bocay',
                'depto' => 'Jinotega',
                'carga_horaria' => 110,
                'inicio' => '9/18/2019',
                'fin' => '10/10/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 127.54,
                'Nombre_del_instructor' => 'Mario Artola',
                'cupos_por_curso' => NULL,
                'H' => 18,
                'M' => 2,
                'total' => 20,
            ),
            108 => 
            array (
                'id' => 109,
                'Nombre_del_curso' => 'Apicultura tropical énfasis BPA',
                'Sector' => 'Agroindustria',
                'Nombre_del_centro' => 'PRONAMIEL',
                'municipio' => 'Somoto',
                'depto' => 'Madriz',
                'carga_horaria' => 110,
                'inicio' => '9/26/2019',
                'fin' => '11/8/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 127.54,
                'Nombre_del_instructor' => 'Danilo Roman Plata',
                'cupos_por_curso' => NULL,
                'H' => NULL,
                'M' => 20,
                'total' => 20,
            ),
            109 => 
            array (
                'id' => 110,
                'Nombre_del_curso' => 'Valor agregado producción de miel y otros productos de la colmena',
                'Sector' => 'Agroindustria',
                'Nombre_del_centro' => 'PRONAMIEL',
                'municipio' => 'Somotillo',
                'depto' => 'Chinandega',
                'carga_horaria' => 94,
                'inicio' => '8/27/2019',
                'fin' => '9/19/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 144.49,
                'Nombre_del_instructor' => 'Maria Elena Matute',
                'cupos_por_curso' => NULL,
                'H' => 9,
                'M' => 9,
                'total' => 18,
            ),
            110 => 
            array (
                'id' => 111,
            'Nombre_del_curso' => 'Especialización en MSS/SOC (análisis de riesgo cibernético)',
                'Sector' => 'Comercio y servicios',
                'Nombre_del_centro' => 'Social Entrepreneurs Group',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 190,
                'inicio' => '10/21/2019',
                'fin' => '12/19/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 700.0,
                'Nombre_del_instructor' => 'Fernando Perez',
                'cupos_por_curso' => NULL,
                'H' => 20,
                'M' => NULL,
                'total' => 20,
            ),
            111 => 
            array (
                'id' => 112,
            'Nombre_del_curso' => 'Especialización en hacking ético (gestión de vulnerabilidad)',
                'Sector' => 'Comercio y servicios',
                'Nombre_del_centro' => 'Social Entrepreneurs Group',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 190,
                'inicio' => '10/21/2019',
                'fin' => '12/19/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 700.0,
                'Nombre_del_instructor' => 'Israel reyes',
                'cupos_por_curso' => NULL,
                'H' => 19,
                'M' => 1,
                'total' => 20,
            ),
            112 => 
            array (
                'id' => 113,
                'Nombre_del_curso' => 'Cocina básica',
                'Sector' => 'Gastronomía',
                'Nombre_del_centro' => 'Vega Baja',
                'municipio' => 'Diriamba',
                'depto' => 'Carazo',
                'carga_horaria' => 230,
                'inicio' => '3/11/2019',
                'fin' => '6/26/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => NULL,
                'Nombre_del_instructor' => '',
                'cupos_por_curso' => NULL,
                'H' => NULL,
                'M' => 17,
                'total' => 17,
            ),
            113 => 
            array (
                'id' => 114,
                'Nombre_del_curso' => 'Corte y confección',
                'Sector' => 'Textil-Vestuario',
                'Nombre_del_centro' => 'Vega Baja',
                'municipio' => 'Diriamba',
                'depto' => 'Carazo',
                'carga_horaria' => 194,
                'inicio' => '3/11/2019',
                'fin' => '6/26/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => NULL,
                'Nombre_del_instructor' => '',
                'cupos_por_curso' => NULL,
                'H' => NULL,
                'M' => 12,
                'total' => 12,
            ),
            114 => 
            array (
                'id' => 115,
                'Nombre_del_curso' => 'Alojamiento',
                'Sector' => 'Alojamiento',
                'Nombre_del_centro' => 'Vega Baja',
                'municipio' => 'Diriamba',
                'depto' => 'Carazo',
                'carga_horaria' => 120,
                'inicio' => '3/13/2019',
                'fin' => '6/28/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => NULL,
                'Nombre_del_instructor' => '',
                'cupos_por_curso' => NULL,
                'H' => NULL,
                'M' => 13,
                'total' => 13,
            ),
            115 => 
            array (
                'id' => 116,
                'Nombre_del_curso' => 'Panadería y bollería',
                'Sector' => 'Agroindustria',
                'Nombre_del_centro' => 'Vega Baja',
                'municipio' => 'Diriamba',
                'depto' => 'Carazo',
                'carga_horaria' => 176,
                'inicio' => '3/13/2019',
                'fin' => '6/27/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => NULL,
                'Nombre_del_instructor' => '',
                'cupos_por_curso' => NULL,
                'H' => NULL,
                'M' => 11,
                'total' => 11,
            ),
            116 => 
            array (
                'id' => 117,
                'Nombre_del_curso' => 'Cocina básica',
                'Sector' => 'Gastronomía',
                'Nombre_del_centro' => 'Vega Baja',
                'municipio' => 'Diriamba',
                'depto' => 'Carazo',
                'carga_horaria' => 270,
                'inicio' => '9/9/2019',
                'fin' => '11/27/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 203.0,
                'Nombre_del_instructor' => 'Gerson Toruño',
                'cupos_por_curso' => NULL,
                'H' => NULL,
                'M' => 28,
                'total' => 28,
            ),
            117 => 
            array (
                'id' => 118,
                'Nombre_del_curso' => 'Corte y confección',
                'Sector' => 'Textil-Vestuario',
                'Nombre_del_centro' => 'Vega Baja',
                'municipio' => 'Diriamba',
                'depto' => 'Carazo',
                'carga_horaria' => 270,
                'inicio' => '9/8/2019',
                'fin' => '11/27/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 260.0,
                'Nombre_del_instructor' => 'Kora Gaitan',
                'cupos_por_curso' => NULL,
                'H' => NULL,
                'M' => 11,
                'total' => 11,
            ),
            118 => 
            array (
                'id' => 119,
                'Nombre_del_curso' => 'Panadería y bollería',
                'Sector' => 'Agroindustria',
                'Nombre_del_centro' => 'Vega Baja',
                'municipio' => 'Diriamba',
                'depto' => 'Carazo',
                'carga_horaria' => 270,
                'inicio' => '9/8/2019',
                'fin' => '11/27/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 202.0,
                'Nombre_del_instructor' => 'Gabriela Ñurinda',
                'cupos_por_curso' => NULL,
                'H' => NULL,
                'M' => 25,
                'total' => 25,
            ),
            119 => 
            array (
                'id' => 120,
                'Nombre_del_curso' => 'Sistema de carga y arranque',
                'Sector' => 'Automotriz',
                'Nombre_del_centro' => 'CET Vocacional',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 80,
                'inicio' => '11/25/2019',
                'fin' => '12/13/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 245.54,
                'Nombre_del_instructor' => 'Ronald Navarrete',
                'cupos_por_curso' => NULL,
                'H' => 15,
                'M' => NULL,
                'total' => 15,
            ),
            120 => 
            array (
                'id' => 121,
                'Nombre_del_curso' => 'Sistema de carga y arranque',
                'Sector' => 'Automotriz',
                'Nombre_del_centro' => 'CET Vocacional',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 80,
                'inicio' => '11/25/2019',
                'fin' => '12/13/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 216.65,
                'Nombre_del_instructor' => 'Ronald Navarrete',
                'cupos_por_curso' => NULL,
                'H' => 17,
                'M' => NULL,
                'total' => 17,
            ),
            121 => 
            array (
                'id' => 122,
                'Nombre_del_curso' => 'Reparación y mantenimiento de motocicleta',
                'Sector' => 'Automotriz',
                'Nombre_del_centro' => 'Fundación Samuel',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 228,
                'inicio' => '9/26/2019',
                'fin' => '12/9/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 171.44,
                'Nombre_del_instructor' => 'Julio Velásquez',
                'cupos_por_curso' => NULL,
                'H' => 20,
                'M' => NULL,
                'total' => 20,
            ),
            122 => 
            array (
                'id' => 123,
                'Nombre_del_curso' => 'Corte y confección',
                'Sector' => 'Textil-Vestuario',
                'Nombre_del_centro' => 'JA Nicaragua',
                'municipio' => 'Managua',
                'depto' => 'Managua',
                'carga_horaria' => 140,
                'inicio' => '04/23/2019',
                'fin' => '06/02/2019',
                'ao' => 2019,
                'costo_por_participante_USD' => 0.0,
                'Nombre_del_instructor' => '',
                'cupos_por_curso' => NULL,
                'H' => NULL,
                'M' => NULL,
                'total' => NULL,
            ),
        ));
        
        
    }
}