<?php

use Illuminate\Database\Seeder;

class FormulariosCamposTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('formularios_campos')->delete();
        
        \DB::table('formularios_campos')->insert(array (
            0 => 
            array (
                'id' => 1122,
                'id_formulario' => 27,
                'id_seccion' => 248,
                'id_tipo' => 1,
                'nombre' => NULL,
                'texto' => 'Como califica la calidad del curso',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 1,
                'respuesta_correcta' => NULL,
                'minimo' => NULL,
                'maximo' => NULL,
                'tipo_input' => '{"id":1,"nombre":"Seleccion Multiple"}',
                'opciones' => '[{"id":1,"nombre":"Malo","respuesta":null},{"id":2,"nombre":"Regular","respuesta":null},{"id":3,"nombre":"Bueno"},{"id":4,"nombre":"Muy bueno"},{"id":5,"nombre":"Excelente"}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            1 => 
            array (
                'id' => 1123,
                'id_formulario' => 27,
                'id_seccion' => 248,
                'id_tipo' => 1,
                'nombre' => NULL,
                'texto' => 'Último grado de educación alcanzado',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 1,
                'respuesta_correcta' => NULL,
                'minimo' => NULL,
                'maximo' => NULL,
                'tipo_input' => '{"id":1,"nombre":"Seleccion Multiple"}',
                'opciones' => '[{"id":1,"nombre":"Primaria","respuesta":null},{"id":2,"nombre":"Secundaria","respuesta":null},{"id":3,"nombre":"Universidad"},{"id":4,"nombre":"T\\u00e9cnico"}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            2 => 
            array (
                'id' => 1124,
                'id_formulario' => 27,
                'id_seccion' => 248,
                'id_tipo' => 2,
                'nombre' => NULL,
                'texto' => 'Escriba el grado',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 1,
                'respuesta_correcta' => NULL,
                'minimo' => NULL,
                'maximo' => NULL,
                'tipo_input' => '{"id":3,"nombre":"Numero","icono":"filter_1"}',
                'opciones' => '[{"id":1,"nombre":"Opcion1","respuesta":null},{"id":2,"nombre":"Opcion2","respuesta":null}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            3 => 
            array (
                'id' => 1125,
                'id_formulario' => 27,
                'id_seccion' => 249,
                'id_tipo' => 1,
                'nombre' => NULL,
                'texto' => '¿Trabaja actualmente?',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 1,
                'respuesta_correcta' => NULL,
                'minimo' => NULL,
                'maximo' => NULL,
                'tipo_input' => '{"id":1,"nombre":"Seleccion Multiple"}',
                'opciones' => '[{"id":1,"nombre":"Si","respuesta":null},{"id":2,"nombre":"No","respuesta":null}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            4 => 
            array (
                'id' => 1126,
                'id_formulario' => 27,
                'id_seccion' => 249,
                'id_tipo' => 1,
                'nombre' => NULL,
                'texto' => '¿Dónde trabaja?',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 0,
                'respuesta_correcta' => NULL,
                'minimo' => NULL,
                'maximo' => NULL,
                'tipo_input' => '{"id":1,"nombre":"Seleccion Multiple"}',
                'opciones' => '[{"id":1,"nombre":"En empresa familiar","respuesta":null},{"id":2,"nombre":"Empresa  no familiar","respuesta":null},{"id":3,"nombre":"Por cuenta propia"}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            5 => 
            array (
                'id' => 1127,
                'id_formulario' => 27,
                'id_seccion' => 249,
                'id_tipo' => 2,
                'nombre' => NULL,
                'texto' => 'Nombre de la empresa o empleador',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 0,
                'respuesta_correcta' => NULL,
                'minimo' => NULL,
                'maximo' => NULL,
                'tipo_input' => '{"id":1,"nombre":"Texto Corto"}',
                'opciones' => '[{"id":1,"nombre":"Opcion1","respuesta":null},{"id":2,"nombre":"Opcion2","respuesta":null}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            6 => 
            array (
                'id' => 1128,
                'id_formulario' => 27,
                'id_seccion' => 249,
                'id_tipo' => 2,
                'nombre' => NULL,
                'texto' => 'Teléfono',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 0,
                'respuesta_correcta' => NULL,
                'minimo' => NULL,
                'maximo' => NULL,
                'tipo_input' => '{"id":1,"nombre":"Texto Corto"}',
                'opciones' => '[{"id":1,"nombre":"Opcion1","respuesta":null},{"id":2,"nombre":"Opcion2","respuesta":null}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            7 => 
            array (
                'id' => 1129,
                'id_formulario' => 27,
                'id_seccion' => 249,
                'id_tipo' => 2,
                'nombre' => NULL,
                'texto' => 'Dirección',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 0,
                'respuesta_correcta' => NULL,
                'minimo' => NULL,
                'maximo' => NULL,
                'tipo_input' => '{"id":1,"nombre":"Texto Corto"}',
                'opciones' => '[{"id":1,"nombre":"Opcion1","respuesta":null},{"id":2,"nombre":"Opcion2","respuesta":null}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            8 => 
            array (
                'id' => 1130,
                'id_formulario' => 27,
                'id_seccion' => 249,
                'id_tipo' => 1,
                'nombre' => NULL,
                'texto' => 'Selecciona la actividad económica principal de la empresa o de su trabajo por cuenta propia',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 1,
                'respuesta_correcta' => NULL,
                'minimo' => NULL,
                'maximo' => NULL,
                'tipo_input' => '{"id":1,"nombre":"Seleccion Multiple"}',
                'opciones' => '[{"id":1,"nombre":"Construcci\\u00f3n","respuesta":null},{"id":2,"nombre":"Electricidad","respuesta":null},{"id":3,"nombre":"Agroindustria"},{"id":4,"nombre":"Agropecuario"},{"id":5,"nombre":"Textil"},{"id":6,"nombre":"Automotriz"},{"id":7,"nombre":"Industria"},{"id":8,"nombre":"Gastronom\\u00eda"},{"id":9,"nombre":"Alojamiento"},{"id":10,"nombre":"Otro"}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            9 => 
            array (
                'id' => 1131,
                'id_formulario' => 27,
                'id_seccion' => 249,
                'id_tipo' => 2,
                'nombre' => NULL,
                'texto' => 'Cargo que desempeña',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 1,
                'respuesta_correcta' => NULL,
                'minimo' => NULL,
                'maximo' => NULL,
                'tipo_input' => '{"id":1,"nombre":"Texto Corto"}',
                'opciones' => '[{"id":1,"nombre":"Opcion1","respuesta":null},{"id":2,"nombre":"Opcion2","respuesta":null}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            10 => 
            array (
                'id' => 1132,
                'id_formulario' => 27,
                'id_seccion' => 249,
                'id_tipo' => 1,
                'nombre' => NULL,
                'texto' => 'El cargo se relaciona con el tema del curso',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 0,
                'respuesta_correcta' => NULL,
                'minimo' => NULL,
                'maximo' => NULL,
                'tipo_input' => '{"id":1,"nombre":"Seleccion Multiple"}',
                'opciones' => '[{"id":1,"nombre":"Si","respuesta":null},{"id":2,"nombre":"No","respuesta":null}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            11 => 
            array (
                'id' => 1133,
                'id_formulario' => 27,
                'id_seccion' => 249,
                'id_tipo' => 4,
                'nombre' => NULL,
                'texto' => 'Departamento',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 1,
                'respuesta_correcta' => NULL,
                'minimo' => '',
                'maximo' => '',
                'tipo_input' => '{"id":1,"nombre":"departamento"}',
                'opciones' => '[{"id":3966,"nombre":"Boaco","id_padre":1438},{"id":3965,"nombre":"Carazo","id_padre":1438},{"id":3967,"nombre":"Caribe Norte","id_padre":1438},{"id":3968,"nombre":"Caribe Sur","id_padre":1438},{"id":3964,"nombre":"Chinandega","id_padre":1438},{"id":3963,"nombre":"Chontales","id_padre":1438},{"id":3962,"nombre":"Estel\\u00ed","id_padre":1438},{"id":3961,"nombre":"Granada","id_padre":1438},{"id":3960,"nombre":"Jinotega","id_padre":1438},{"id":3959,"nombre":"Le\\u00f3n","id_padre":1438},{"id":3958,"nombre":"Madriz","id_padre":1438},{"id":3957,"nombre":"Managua","id_padre":1438},{"id":3956,"nombre":"Masaya","id_padre":1438},{"id":3955,"nombre":"Matagalpa","id_padre":1438},{"id":3954,"nombre":"Nueva Segovia","id_padre":1438},{"id":3953,"nombre":"R\\u00edo San Juan","id_padre":1438},{"id":3952,"nombre":"Rivas","id_padre":1438}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            12 => 
            array (
                'id' => 1134,
                'id_formulario' => 27,
                'id_seccion' => 249,
                'id_tipo' => 5,
                'nombre' => NULL,
                'texto' => 'Municipio',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 1,
                'respuesta_correcta' => NULL,
                'minimo' => '',
                'maximo' => '',
                'tipo_input' => '{"id":1,"nombre":"municipio"}',
                'opciones' => '[]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            13 => 
            array (
                'id' => 1135,
                'id_formulario' => 27,
                'id_seccion' => 249,
                'id_tipo' => 2,
                'nombre' => NULL,
            'texto' => '¿Cuánto gana al mes (en Córdobas)?',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 0,
                'respuesta_correcta' => NULL,
                'minimo' => NULL,
                'maximo' => NULL,
                'tipo_input' => '{"id":3,"nombre":"Numero","icono":"filter_1"}',
                'opciones' => '[{"id":1,"nombre":"Opcion1","respuesta":null},{"id":2,"nombre":"Opcion2","respuesta":null}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            14 => 
            array (
                'id' => 1136,
                'id_formulario' => 27,
                'id_seccion' => 249,
                'id_tipo' => 2,
                'nombre' => NULL,
                'texto' => '¿Cuántos años tiene de estar en ese trabajo?',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 0,
                'respuesta_correcta' => NULL,
                'minimo' => NULL,
                'maximo' => NULL,
                'tipo_input' => '{"id":3,"nombre":"Numero","icono":"filter_1"}',
                'opciones' => '[{"id":1,"nombre":"Opcion1","respuesta":null},{"id":2,"nombre":"Opcion2","respuesta":null}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            15 => 
            array (
                'id' => 1137,
                'id_formulario' => 27,
                'id_seccion' => 249,
                'id_tipo' => 2,
                'nombre' => NULL,
                'texto' => '¿Cuántos días a la semana trabaja?',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 0,
                'respuesta_correcta' => NULL,
                'minimo' => NULL,
                'maximo' => NULL,
                'tipo_input' => '{"id":3,"nombre":"Numero","icono":"filter_1"}',
                'opciones' => '[{"id":1,"nombre":"Opcion1","respuesta":null},{"id":2,"nombre":"Opcion2","respuesta":null}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            16 => 
            array (
                'id' => 1138,
                'id_formulario' => 27,
                'id_seccion' => 249,
                'id_tipo' => 2,
                'nombre' => NULL,
                'texto' => '¿Cuántas horas al día trabaja?',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 0,
                'respuesta_correcta' => NULL,
                'minimo' => NULL,
                'maximo' => NULL,
                'tipo_input' => '{"id":3,"nombre":"Numero","icono":"filter_1"}',
                'opciones' => '[{"id":1,"nombre":"Opcion1","respuesta":null},{"id":2,"nombre":"Opcion2","respuesta":null}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            17 => 
            array (
                'id' => 1139,
                'id_formulario' => 27,
                'id_seccion' => 249,
                'id_tipo' => 1,
                'nombre' => NULL,
                'texto' => 'Que lo motivó a participar en este curso',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 1,
                'respuesta_correcta' => NULL,
                'minimo' => NULL,
                'maximo' => NULL,
                'tipo_input' => '{"id":1,"nombre":"Seleccion Multiple"}',
                'opciones' => '[{"id":1,"nombre":"La capacitaci\\u00f3n fue exigida por  mi empleador","respuesta":null},{"id":2,"nombre":"Quiero obtener otros conocimientos para cambiar de ocupaci\\u00f3n","respuesta":null},{"id":3,"nombre":"Necesito aumentar mis ingresos"},{"id":4,"nombre":"Quiero ampliar mis conocimientos en un \\u00e1rea espec\\u00edfica"},{"id":5,"nombre":"Otro"}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            18 => 
            array (
                'id' => 1140,
                'id_formulario' => 27,
                'id_seccion' => 249,
                'id_tipo' => 2,
                'nombre' => NULL,
            'texto' => 'Otro Especifique (en caso de seleccionar otro en la opción anterior)',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 0,
                'respuesta_correcta' => NULL,
                'minimo' => NULL,
                'maximo' => NULL,
                'tipo_input' => '{"id":1,"nombre":"Texto Corto"}',
                'opciones' => '[{"id":1,"nombre":"Opcion1","respuesta":null},{"id":2,"nombre":"Opcion2","respuesta":null}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            19 => 
            array (
                'id' => 1141,
                'id_formulario' => 27,
                'id_seccion' => 249,
                'id_tipo' => 1,
                'nombre' => NULL,
                'texto' => 'Para los que no trabajan, ¿Que lo motivó a participar en este curso?',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 1,
                'respuesta_correcta' => NULL,
                'minimo' => NULL,
                'maximo' => NULL,
                'tipo_input' => '{"id":1,"nombre":"Seleccion Multiple"}',
                'opciones' => '[{"id":1,"nombre":"Obtener un empleo","respuesta":null},{"id":2,"nombre":"Iniciar un negocio propio","respuesta":null},{"id":3,"nombre":"Prepararme para estudios posteriores"},{"id":4,"nombre":"Otro"}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            20 => 
            array (
                'id' => 1142,
                'id_formulario' => 27,
                'id_seccion' => 249,
                'id_tipo' => 2,
                'nombre' => NULL,
            'texto' => 'Otro (especifique)',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 0,
                'respuesta_correcta' => NULL,
                'minimo' => NULL,
                'maximo' => NULL,
                'tipo_input' => '{"id":1,"nombre":"Texto Corto"}',
                'opciones' => '[{"id":1,"nombre":"Opcion1","respuesta":null},{"id":2,"nombre":"Opcion2","respuesta":null}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            21 => 
            array (
                'id' => 1143,
                'id_formulario' => 27,
                'id_seccion' => 249,
                'id_tipo' => 6,
                'nombre' => NULL,
                'texto' => '¿Qué tan probable es que recomiendes este curso a tus amigos o familiares? , Califique del 1 al 10',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 1,
                'respuesta_correcta' => NULL,
                'minimo' => '',
                'maximo' => '',
                'tipo_input' => '{"id":1,"nombre":"Seleccion Multiple"}',
                'opciones' => '[{"id":1,"nombre":"Opci\\u00f3n1","respuesta":null,"nota":0},{"id":2,"nombre":"Opci\\u00f3n2","respuesta":null,"nota":0}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            22 => 
            array (
                'id' => 1165,
                'id_formulario' => 29,
                'id_seccion' => 256,
                'id_tipo' => 1,
                'nombre' => NULL,
                'texto' => 'Al inicio del curso el instructor me informó sobre las competencias a desarrollar, el horario y la duración?',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 1,
                'respuesta_correcta' => NULL,
                'minimo' => '',
                'maximo' => '',
                'tipo_input' => '{"id":1,"nombre":"Seleccion Multiple"}',
                'opciones' => '[{"id":1,"nombre":"Si","respuesta":null,"nota":0},{"id":2,"nombre":"No","respuesta":null,"nota":0}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            23 => 
            array (
                'id' => 1166,
                'id_formulario' => 29,
                'id_seccion' => 256,
                'id_tipo' => 1,
                'nombre' => NULL,
                'texto' => 'Asisto a las clases todos los días ?',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 1,
                'respuesta_correcta' => NULL,
                'minimo' => '',
                'maximo' => '',
                'tipo_input' => '{"id":1,"nombre":"Seleccion Multiple"}',
                'opciones' => '[{"id":1,"nombre":"Si","respuesta":null,"nota":0},{"id":2,"nombre":"No","respuesta":null,"nota":0}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            24 => 
            array (
                'id' => 1167,
                'id_formulario' => 29,
                'id_seccion' => 256,
                'id_tipo' => 1,
                'nombre' => NULL,
                'texto' => 'Cumplo con el horario establecido?',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 1,
                'respuesta_correcta' => NULL,
                'minimo' => '',
                'maximo' => '',
                'tipo_input' => '{"id":1,"nombre":"Seleccion Multiple"}',
                'opciones' => '[{"id":1,"nombre":"Opci\\u00f3n1","respuesta":null,"nota":0},{"id":2,"nombre":"Opci\\u00f3n2","respuesta":null,"nota":0}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            25 => 
            array (
                'id' => 1168,
                'id_formulario' => 29,
                'id_seccion' => 256,
                'id_tipo' => 1,
                'nombre' => NULL,
                'texto' => 'El instructor cumple con el horario de las clases?',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 1,
                'respuesta_correcta' => NULL,
                'minimo' => '',
                'maximo' => '',
                'tipo_input' => '{"id":1,"nombre":"Seleccion Multiple"}',
                'opciones' => '[{"id":1,"nombre":"Si","respuesta":null,"nota":0},{"id":2,"nombre":"No","respuesta":null,"nota":0}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            26 => 
            array (
                'id' => 1169,
                'id_formulario' => 29,
                'id_seccion' => 257,
                'id_tipo' => 1,
                'nombre' => NULL,
                'texto' => 'Al inicio del curso me entregaron los manuales del participante?',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 1,
                'respuesta_correcta' => NULL,
                'minimo' => '',
                'maximo' => '',
                'tipo_input' => '{"id":1,"nombre":"Seleccion Multiple"}',
                'opciones' => '[{"id":1,"nombre":"Si","respuesta":null,"nota":0},{"id":2,"nombre":"No","respuesta":null,"nota":0}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            27 => 
            array (
                'id' => 1170,
                'id_formulario' => 29,
                'id_seccion' => 257,
                'id_tipo' => 1,
                'nombre' => NULL,
                'texto' => 'El material didáctico utilizado en la clase es variado y adecuado para la adquisición del conocimiento',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 1,
                'respuesta_correcta' => NULL,
                'minimo' => '',
                'maximo' => '',
                'tipo_input' => '{"id":1,"nombre":"Seleccion Multiple"}',
                'opciones' => '[{"id":1,"nombre":"Si","respuesta":null,"nota":0},{"id":2,"nombre":"No","respuesta":null,"nota":0}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            28 => 
            array (
                'id' => 1171,
                'id_formulario' => 29,
                'id_seccion' => 257,
                'id_tipo' => 1,
                'nombre' => NULL,
                'texto' => 'Los equipos, herramientas e insumos utilizados en la clase son suficientes para realizar las prácticas?',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 1,
                'respuesta_correcta' => NULL,
                'minimo' => '',
                'maximo' => '',
                'tipo_input' => '{"id":1,"nombre":"Seleccion Multiple"}',
                'opciones' => '[{"id":1,"nombre":"Si","respuesta":null,"nota":0},{"id":2,"nombre":"No","respuesta":null,"nota":0}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            29 => 
            array (
                'id' => 1172,
                'id_formulario' => 29,
                'id_seccion' => 257,
                'id_tipo' => 1,
                'nombre' => NULL,
                'texto' => 'Los equipos, herramientas e instalaciones se encontraban en buen estado para realizar las prácticas',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 1,
                'respuesta_correcta' => NULL,
                'minimo' => '',
                'maximo' => '',
                'tipo_input' => '{"id":1,"nombre":"Seleccion Multiple"}',
                'opciones' => '[{"id":1,"nombre":"Si","respuesta":null,"nota":0},{"id":2,"nombre":"No","respuesta":null,"nota":0}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            30 => 
            array (
                'id' => 1173,
                'id_formulario' => 29,
                'id_seccion' => 258,
                'id_tipo' => 1,
                'nombre' => NULL,
                'texto' => 'El instructor demuestra dominio de los temas teóricos y prácticos?',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 1,
                'respuesta_correcta' => NULL,
                'minimo' => '',
                'maximo' => '',
                'tipo_input' => '{"id":1,"nombre":"Seleccion Multiple"}',
                'opciones' => '[{"id":1,"nombre":"Si","respuesta":null,"nota":0},{"id":2,"nombre":"No","respuesta":null,"nota":0}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            31 => 
            array (
                'id' => 1174,
                'id_formulario' => 29,
                'id_seccion' => 258,
                'id_tipo' => 1,
                'nombre' => NULL,
                'texto' => 'El instructor orienta de forma clara  las actividades que se realizan durante el curso?',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 1,
                'respuesta_correcta' => NULL,
                'minimo' => '',
                'maximo' => '',
                'tipo_input' => '{"id":1,"nombre":"Seleccion Multiple"}',
                'opciones' => '[{"id":1,"nombre":"Si","respuesta":null,"nota":0},{"id":2,"nombre":"No","respuesta":null,"nota":0}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            32 => 
            array (
                'id' => 1175,
                'id_formulario' => 29,
                'id_seccion' => 258,
                'id_tipo' => 1,
                'nombre' => NULL,
                'texto' => 'Logra mantener el interés sobre los contenidos de estudio?',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 1,
                'respuesta_correcta' => NULL,
                'minimo' => '',
                'maximo' => '',
                'tipo_input' => '{"id":1,"nombre":"Seleccion Multiple"}',
                'opciones' => '[{"id":1,"nombre":"Si","respuesta":null,"nota":0},{"id":2,"nombre":"No","respuesta":null,"nota":0}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            33 => 
            array (
                'id' => 1176,
                'id_formulario' => 29,
                'id_seccion' => 258,
                'id_tipo' => 1,
                'nombre' => NULL,
                'texto' => 'Las clases teóricas y prácticas le facilitan la comprensión y aplicación de los conocimientos?',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 1,
                'respuesta_correcta' => NULL,
                'minimo' => '',
                'maximo' => '',
                'tipo_input' => '{"id":1,"nombre":"Seleccion Multiple"}',
                'opciones' => '[{"id":1,"nombre":"Si","respuesta":null,"nota":0},{"id":2,"nombre":"No","respuesta":null,"nota":0}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            34 => 
            array (
                'id' => 1177,
                'id_formulario' => 29,
                'id_seccion' => 258,
                'id_tipo' => 1,
                'nombre' => NULL,
                'texto' => 'Después de una evaluación el instructor le señala los errores y le indica la mejor manera de resolverlos?',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 1,
                'respuesta_correcta' => NULL,
                'minimo' => '',
                'maximo' => '',
                'tipo_input' => '{"id":1,"nombre":"Seleccion Multiple"}',
                'opciones' => '[{"id":1,"nombre":"Si","respuesta":null,"nota":0},{"id":2,"nombre":"No","respuesta":null,"nota":0}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            35 => 
            array (
                'id' => 1178,
                'id_formulario' => 29,
                'id_seccion' => 259,
                'id_tipo' => 1,
                'nombre' => NULL,
                'texto' => 'La ubicación de los equipos y la organización del espacio facilita la realización de las prácticas?',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 1,
                'respuesta_correcta' => NULL,
                'minimo' => '',
                'maximo' => '',
                'tipo_input' => '{"id":1,"nombre":"Seleccion Multiple"}',
                'opciones' => '[{"id":1,"nombre":"Si","respuesta":null,"nota":0},{"id":2,"nombre":"No","respuesta":null,"nota":0}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            36 => 
            array (
                'id' => 1179,
                'id_formulario' => 29,
                'id_seccion' => 259,
                'id_tipo' => 1,
                'nombre' => NULL,
            'texto' => 'Las clases teóricas se desarrollan en espacios acondicionados (silla, mesa o pupitre, iluminación. otro.)?',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 1,
                'respuesta_correcta' => NULL,
                'minimo' => '',
                'maximo' => '',
                'tipo_input' => '{"id":1,"nombre":"Seleccion Multiple"}',
                'opciones' => '[{"id":1,"nombre":"Si","respuesta":null,"nota":0},{"id":2,"nombre":"No","respuesta":null,"nota":0}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            37 => 
            array (
                'id' => 1180,
                'id_formulario' => 29,
                'id_seccion' => 259,
                'id_tipo' => 1,
                'nombre' => NULL,
            'texto' => 'Las clases prácticas se desarrollan en lugares apropiados (talleres o espacios equipados y condicionados)?',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 1,
                'respuesta_correcta' => NULL,
                'minimo' => '',
                'maximo' => '',
                'tipo_input' => '{"id":1,"nombre":"Seleccion Multiple"}',
                'opciones' => '[{"id":1,"nombre":"Si","respuesta":null,"nota":0},{"id":2,"nombre":"No","respuesta":null,"nota":0}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            38 => 
            array (
                'id' => 1181,
                'id_formulario' => 29,
                'id_seccion' => 260,
                'id_tipo' => 1,
                'nombre' => NULL,
                'texto' => 'El instructor permite la participación de hombres y mujeres por igual?',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 1,
                'respuesta_correcta' => NULL,
                'minimo' => '',
                'maximo' => '',
                'tipo_input' => '{"id":1,"nombre":"Seleccion Multiple"}',
                'opciones' => '[{"id":1,"nombre":"Si","respuesta":null,"nota":0},{"id":2,"nombre":"No","respuesta":null,"nota":0}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            39 => 
            array (
                'id' => 1182,
                'id_formulario' => 29,
                'id_seccion' => 260,
                'id_tipo' => 1,
                'nombre' => NULL,
                'texto' => 'El instructor desarrolla alguna de estas actividades o temas: trabajo en equipo, comunicación,  proactividad, aprender a aprender, resolución de problemas, creatividad?',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 1,
                'respuesta_correcta' => NULL,
                'minimo' => '',
                'maximo' => '',
                'tipo_input' => '{"id":1,"nombre":"Seleccion Multiple"}',
                'opciones' => '[{"id":1,"nombre":"Si","respuesta":null,"nota":0},{"id":2,"nombre":"No","respuesta":null,"nota":0}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            40 => 
            array (
                'id' => 1183,
                'id_formulario' => 29,
                'id_seccion' => 260,
                'id_tipo' => 1,
                'nombre' => NULL,
                'texto' => 'El instructor desarrolla temas o prácticas para saber como emprender un negocio o autoempleo?',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 1,
                'respuesta_correcta' => NULL,
                'minimo' => '',
                'maximo' => '',
                'tipo_input' => '{"id":1,"nombre":"Seleccion Multiple"}',
                'opciones' => '[{"id":1,"nombre":"Si","respuesta":null,"nota":0},{"id":2,"nombre":"No","respuesta":null,"nota":0}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            41 => 
            array (
                'id' => 1184,
                'id_formulario' => 29,
                'id_seccion' => 261,
                'id_tipo' => 1,
                'nombre' => NULL,
                'texto' => 'Considero que el curso me permitirá obtener un empleo o iniciar un emprendimiento?',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 1,
                'respuesta_correcta' => NULL,
                'minimo' => '',
                'maximo' => '',
                'tipo_input' => '{"id":1,"nombre":"Seleccion Multiple"}',
                'opciones' => '[{"id":1,"nombre":"Si","respuesta":null,"nota":0},{"id":2,"nombre":"No","respuesta":null,"nota":0}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            42 => 
            array (
                'id' => 1185,
                'id_formulario' => 29,
                'id_seccion' => 261,
                'id_tipo' => 1,
                'nombre' => NULL,
                'texto' => 'Considero que he alcanzado los resultados de aprendizaje propuestos en el curso?',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 1,
                'respuesta_correcta' => NULL,
                'minimo' => '',
                'maximo' => '',
                'tipo_input' => '{"id":1,"nombre":"Seleccion Multiple"}',
                'opciones' => '[{"id":1,"nombre":"Si","respuesta":null,"nota":0},{"id":2,"nombre":"No","respuesta":null,"nota":0}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            43 => 
            array (
                'id' => 1296,
                'id_formulario' => 30,
                'id_seccion' => 272,
                'id_tipo' => 1,
                'nombre' => NULL,
                'texto' => 'Último grado de educación alcanzado',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 1,
                'respuesta_correcta' => NULL,
                'minimo' => NULL,
                'maximo' => NULL,
                'tipo_input' => '{"id":1,"nombre":"Seleccion Multiple"}',
                'opciones' => '[{"id":1,"nombre":"Primaria","respuesta":null},{"id":2,"nombre":"Secundaria","respuesta":null},{"id":3,"nombre":"Universidad"},{"id":4,"nombre":"T\\u00e9cnico"}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            44 => 
            array (
                'id' => 1297,
                'id_formulario' => 30,
                'id_seccion' => 272,
                'id_tipo' => 2,
                'nombre' => NULL,
                'texto' => 'Escriba el grado',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 1,
                'respuesta_correcta' => NULL,
                'minimo' => NULL,
                'maximo' => NULL,
                'tipo_input' => '{"id":3,"nombre":"Numero","icono":"filter_1"}',
                'opciones' => '[{"id":1,"nombre":"Opcion1","respuesta":null},{"id":2,"nombre":"Opcion2","respuesta":null}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            45 => 
            array (
                'id' => 1298,
                'id_formulario' => 30,
                'id_seccion' => 272,
                'id_tipo' => 1,
                'nombre' => NULL,
                'texto' => 'Como califica la calidad del curso',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 1,
                'respuesta_correcta' => NULL,
                'minimo' => NULL,
                'maximo' => NULL,
                'tipo_input' => '{"id":1,"nombre":"Seleccion Multiple"}',
                'opciones' => '[{"id":1,"nombre":"Malo","respuesta":null},{"id":2,"nombre":"Regular","respuesta":null},{"id":3,"nombre":"Bueno"},{"id":4,"nombre":"Muy bueno"},{"id":5,"nombre":"Excelente"}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            46 => 
            array (
                'id' => 1299,
                'id_formulario' => 30,
                'id_seccion' => 273,
                'id_tipo' => 1,
                'nombre' => NULL,
                'texto' => '¿Trabaja actualmente?',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 1,
                'respuesta_correcta' => NULL,
                'minimo' => NULL,
                'maximo' => NULL,
                'tipo_input' => '{"id":1,"nombre":"Seleccion Multiple"}',
                'opciones' => '[{"id":1,"nombre":"Si","respuesta":null},{"id":2,"nombre":"No","respuesta":null}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            47 => 
            array (
                'id' => 1300,
                'id_formulario' => 30,
                'id_seccion' => 273,
                'id_tipo' => 1,
                'nombre' => NULL,
                'texto' => '¿Dónde trabaja?',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 0,
                'respuesta_correcta' => NULL,
                'minimo' => NULL,
                'maximo' => NULL,
                'tipo_input' => '{"id":1,"nombre":"Seleccion Multiple"}',
                'opciones' => '[{"id":1,"nombre":"En empresa familiar","respuesta":null},{"id":2,"nombre":"Empresa  no familiar","respuesta":null},{"id":3,"nombre":"Por cuenta propia"}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            48 => 
            array (
                'id' => 1301,
                'id_formulario' => 30,
                'id_seccion' => 273,
                'id_tipo' => 2,
                'nombre' => NULL,
                'texto' => 'Nombre de la empresa o empleador',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 0,
                'respuesta_correcta' => NULL,
                'minimo' => NULL,
                'maximo' => NULL,
                'tipo_input' => '{"id":1,"nombre":"Texto Corto"}',
                'opciones' => '[{"id":1,"nombre":"Opcion1","respuesta":null},{"id":2,"nombre":"Opcion2","respuesta":null}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            49 => 
            array (
                'id' => 1302,
                'id_formulario' => 30,
                'id_seccion' => 273,
                'id_tipo' => 2,
                'nombre' => NULL,
                'texto' => 'Teléfono empresa',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 0,
                'respuesta_correcta' => NULL,
                'minimo' => NULL,
                'maximo' => NULL,
                'tipo_input' => '{"id":1,"nombre":"Texto Corto"}',
                'opciones' => '[{"id":1,"nombre":"Opcion1","respuesta":null},{"id":2,"nombre":"Opcion2","respuesta":null}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            50 => 
            array (
                'id' => 1303,
                'id_formulario' => 30,
                'id_seccion' => 273,
                'id_tipo' => 2,
                'nombre' => NULL,
                'texto' => 'Dirección empresa',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 0,
                'respuesta_correcta' => NULL,
                'minimo' => NULL,
                'maximo' => NULL,
                'tipo_input' => '{"id":1,"nombre":"Texto Corto"}',
                'opciones' => '[{"id":1,"nombre":"Opcion1","respuesta":null},{"id":2,"nombre":"Opcion2","respuesta":null}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            51 => 
            array (
                'id' => 1304,
                'id_formulario' => 30,
                'id_seccion' => 273,
                'id_tipo' => 1,
                'nombre' => NULL,
                'texto' => 'Selecciona la actividad económica principal de la empresa o de su trabajo por cuenta propia',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 1,
                'respuesta_correcta' => NULL,
                'minimo' => NULL,
                'maximo' => NULL,
                'tipo_input' => '{"id":1,"nombre":"Seleccion Multiple"}',
                'opciones' => '[{"id":3,"nombre":"Agroindustria"},{"id":9,"nombre":"Alojamiento"},{"id":11,"nombre":"Artesan\\u00eda","respuesta":null,"nota":0},{"id":6,"nombre":"Automotriz"},{"id":12,"nombre":"Comercio y servicios","respuesta":null,"nota":0},{"id":11,"nombre":"Comider\\u00eda","respuesta":null,"nota":0},{"id":1,"nombre":"Construcci\\u00f3n","respuesta":null},{"id":11,"nombre":"Educaci\\u00f3n","respuesta":null,"nota":0},{"id":2,"nombre":"Electricidad","respuesta":null},{"id":4,"nombre":"Gastronom\\u00eda"},{"id":5,"nombre":"Gobierno"},{"id":7,"nombre":"Industria"},{"id":8,"nombre":"Inform\\u00e1tica"},{"id":10,"nombre":"Madera mueble"},{"id":11,"nombre":"Miner\\u00eda","respuesta":null,"nota":0},{"id":12,"nombre":"Planificaci\\u00f3n","respuesta":null,"nota":0},{"id":13,"nombre":"Salud","respuesta":null,"nota":0},{"id":14,"nombre":"Textil","respuesta":null,"nota":0},{"id":15,"nombre":"Turismo","respuesta":null,"nota":0}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            52 => 
            array (
                'id' => 1305,
                'id_formulario' => 30,
                'id_seccion' => 273,
                'id_tipo' => 2,
                'nombre' => NULL,
                'texto' => 'Cargo que desempeña',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 1,
                'respuesta_correcta' => NULL,
                'minimo' => NULL,
                'maximo' => NULL,
                'tipo_input' => '{"id":1,"nombre":"Texto Corto"}',
                'opciones' => '[{"id":1,"nombre":"Opcion1","respuesta":null},{"id":2,"nombre":"Opcion2","respuesta":null}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            53 => 
            array (
                'id' => 1306,
                'id_formulario' => 30,
                'id_seccion' => 273,
                'id_tipo' => 1,
                'nombre' => NULL,
                'texto' => 'El cargo se relaciona con el tema del curso',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 0,
                'respuesta_correcta' => NULL,
                'minimo' => NULL,
                'maximo' => NULL,
                'tipo_input' => '{"id":1,"nombre":"Seleccion Multiple"}',
                'opciones' => '[{"id":1,"nombre":"Si","respuesta":null},{"id":2,"nombre":"No","respuesta":null}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            54 => 
            array (
                'id' => 1307,
                'id_formulario' => 30,
                'id_seccion' => 273,
                'id_tipo' => 4,
                'nombre' => NULL,
                'texto' => 'Departamento',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 1,
                'respuesta_correcta' => NULL,
                'minimo' => '',
                'maximo' => '',
                'tipo_input' => '{"id":1,"nombre":"departamento"}',
                'opciones' => '[{"id":3966,"nombre":"Boaco","id_padre":1438},{"id":3965,"nombre":"Carazo","id_padre":1438},{"id":3967,"nombre":"Caribe Norte","id_padre":1438},{"id":3968,"nombre":"Caribe Sur","id_padre":1438},{"id":3964,"nombre":"Chinandega","id_padre":1438},{"id":3963,"nombre":"Chontales","id_padre":1438},{"id":3962,"nombre":"Estel\\u00ed","id_padre":1438},{"id":3961,"nombre":"Granada","id_padre":1438},{"id":3960,"nombre":"Jinotega","id_padre":1438},{"id":3959,"nombre":"Le\\u00f3n","id_padre":1438},{"id":3958,"nombre":"Madriz","id_padre":1438},{"id":3957,"nombre":"Managua","id_padre":1438},{"id":3956,"nombre":"Masaya","id_padre":1438},{"id":3955,"nombre":"Matagalpa","id_padre":1438},{"id":3954,"nombre":"Nueva Segovia","id_padre":1438},{"id":3953,"nombre":"R\\u00edo San Juan","id_padre":1438},{"id":3952,"nombre":"Rivas","id_padre":1438}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            55 => 
            array (
                'id' => 1308,
                'id_formulario' => 30,
                'id_seccion' => 273,
                'id_tipo' => 5,
                'nombre' => NULL,
                'texto' => 'Municipio',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 1,
                'respuesta_correcta' => NULL,
                'minimo' => '',
                'maximo' => '',
                'tipo_input' => '{"id":1,"nombre":"municipio"}',
                'opciones' => '[]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            56 => 
            array (
                'id' => 1309,
                'id_formulario' => 30,
                'id_seccion' => 273,
                'id_tipo' => 2,
                'nombre' => NULL,
            'texto' => '¿Cuánto gana al mes (en Córdobas)?',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 0,
                'respuesta_correcta' => NULL,
                'minimo' => NULL,
                'maximo' => NULL,
                'tipo_input' => '{"id":3,"nombre":"Numero","icono":"filter_1"}',
                'opciones' => '[{"id":1,"nombre":"Opcion1","respuesta":null},{"id":2,"nombre":"Opcion2","respuesta":null}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            57 => 
            array (
                'id' => 1310,
                'id_formulario' => 30,
                'id_seccion' => 273,
                'id_tipo' => 2,
                'nombre' => NULL,
                'texto' => '¿Cuántos años tiene de estar en ese trabajo?',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 0,
                'respuesta_correcta' => NULL,
                'minimo' => NULL,
                'maximo' => NULL,
                'tipo_input' => '{"id":3,"nombre":"Numero","icono":"filter_1"}',
                'opciones' => '[{"id":1,"nombre":"Opcion1","respuesta":null},{"id":2,"nombre":"Opcion2","respuesta":null}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            58 => 
            array (
                'id' => 1311,
                'id_formulario' => 30,
                'id_seccion' => 273,
                'id_tipo' => 2,
                'nombre' => NULL,
                'texto' => '¿Cuántos días a la semana trabaja?',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 0,
                'respuesta_correcta' => NULL,
                'minimo' => NULL,
                'maximo' => NULL,
                'tipo_input' => '{"id":3,"nombre":"Numero","icono":"filter_1"}',
                'opciones' => '[{"id":1,"nombre":"Opcion1","respuesta":null},{"id":2,"nombre":"Opcion2","respuesta":null}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            59 => 
            array (
                'id' => 1312,
                'id_formulario' => 30,
                'id_seccion' => 273,
                'id_tipo' => 2,
                'nombre' => NULL,
                'texto' => '¿Cuántas horas al día trabaja?',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 0,
                'respuesta_correcta' => NULL,
                'minimo' => NULL,
                'maximo' => NULL,
                'tipo_input' => '{"id":3,"nombre":"Numero","icono":"filter_1"}',
                'opciones' => '[{"id":1,"nombre":"Opcion1","respuesta":null},{"id":2,"nombre":"Opcion2","respuesta":null}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            60 => 
            array (
                'id' => 1313,
                'id_formulario' => 30,
                'id_seccion' => 273,
                'id_tipo' => 1,
                'nombre' => NULL,
                'texto' => 'Que lo motivó a participar en este curso',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 1,
                'respuesta_correcta' => NULL,
                'minimo' => NULL,
                'maximo' => NULL,
                'tipo_input' => '{"id":1,"nombre":"Seleccion Multiple"}',
                'opciones' => '[{"id":1,"nombre":"La capacitaci\\u00f3n fue exigida por  mi empleador","respuesta":null},{"id":2,"nombre":"Quiero obtener otros conocimientos para cambiar de ocupaci\\u00f3n","respuesta":null},{"id":3,"nombre":"Necesito aumentar mis ingresos"},{"id":4,"nombre":"Quiero ampliar mis conocimientos en un \\u00e1rea espec\\u00edfica"},{"id":5,"nombre":"Otro"}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            61 => 
            array (
                'id' => 1314,
                'id_formulario' => 30,
                'id_seccion' => 273,
                'id_tipo' => 2,
                'nombre' => NULL,
            'texto' => 'Otro Especifique (en caso de seleccionar otro en la opción anterior)',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 0,
                'respuesta_correcta' => NULL,
                'minimo' => NULL,
                'maximo' => NULL,
                'tipo_input' => '{"id":1,"nombre":"Texto Corto"}',
                'opciones' => '[{"id":1,"nombre":"Opcion1","respuesta":null},{"id":2,"nombre":"Opcion2","respuesta":null}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            62 => 
            array (
                'id' => 1315,
                'id_formulario' => 30,
                'id_seccion' => 273,
                'id_tipo' => 1,
                'nombre' => NULL,
                'texto' => 'Para los que no trabajan, ¿Que lo motivó a participar en este curso?',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 1,
                'respuesta_correcta' => NULL,
                'minimo' => NULL,
                'maximo' => NULL,
                'tipo_input' => '{"id":1,"nombre":"Seleccion Multiple"}',
                'opciones' => '[{"id":1,"nombre":"Obtener un empleo","respuesta":null},{"id":2,"nombre":"Iniciar un negocio propio","respuesta":null},{"id":3,"nombre":"Prepararme para estudios posteriores"},{"id":4,"nombre":"Otro"}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            63 => 
            array (
                'id' => 1316,
                'id_formulario' => 30,
                'id_seccion' => 273,
                'id_tipo' => 2,
                'nombre' => NULL,
            'texto' => 'Otro (especifique)',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 0,
                'respuesta_correcta' => NULL,
                'minimo' => NULL,
                'maximo' => NULL,
                'tipo_input' => '{"id":1,"nombre":"Texto Corto"}',
                'opciones' => '[{"id":1,"nombre":"Opcion1","respuesta":null},{"id":2,"nombre":"Opcion2","respuesta":null}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
            64 => 
            array (
                'id' => 1317,
                'id_formulario' => 30,
                'id_seccion' => 273,
                'id_tipo' => 6,
                'nombre' => NULL,
                'texto' => '¿Qué tan probable es que recomiendes este curso a tus amigos o familiares? , Califique del 1 al 10',
                'subtitulo' => NULL,
                'imagen' => NULL,
                'requerido' => 1,
                'respuesta_correcta' => NULL,
                'minimo' => '',
                'maximo' => '',
                'tipo_input' => '{"id":1,"nombre":"Seleccion Multiple"}',
                'opciones' => '[{"id":1,"nombre":"Opci\\u00f3n1","respuesta":null,"nota":0},{"id":2,"nombre":"Opci\\u00f3n2","respuesta":null,"nota":0}]',
                'nota' => '0.00',
                'editando' => 0,
                'temp' => NULL,
                'respuesta' => NULL,
                'arregloTable' => NULL,
            ),
        ));
        
        
    }
}