<?php

use Illuminate\Database\Seeder;

class UsuariosTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('usuarios')->delete();
        
        \DB::table('usuarios')->insert(array (
            0 => 
            array (
                'id' => 1,
                'nombre' => 'Super Usuario',
                'email' => 'czambrana@innovactioncorp.com',
                'fecha_verificacion_email' => '2020-01-27 07:55:59',
                'token_email_confirmation' => NULL,
                'password' => '$2y$10$FP.bncMFy1lb.7INl3mg7u2KtplAk2zRyzV7sH2Jby4HyBWJzgzHy',
                'imagen' => NULL,
                'remember_token' => 'AlB4hKVg4i',
                'created_at' => '2019-07-23 15:10:53',
                'updated_at' => '2020-01-27 07:55:59',
                'deleted_at' => NULL,
                'id_rol' => 1,
            ),
            1 => 
            array (
                'id' => 29,
                'nombre' => 'Jennywell Pérez miranda',
                'email' => 'jennywellmiranda@gmail.com',
                'fecha_verificacion_email' => NULL,
                'token_email_confirmation' => 'hTKkXyDHnuRb2Ru83ypentqwAh6giY',
                'password' => '$2y$10$v1zByhfZT6EzLvsljl7b1uzy9GEX2kHCIx7roq8jTuIVXMfMbH8Zi',
                'imagen' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-10-07 04:18:29',
                'updated_at' => '2019-10-19 17:50:49',
                'deleted_at' => NULL,
                'id_rol' => 5,
            ),
            2 => 
            array (
                'id' => 30,
                'nombre' => 'Carolina Lissete Centeno Rivera',
                'email' => 'ccentenorivera@gmail.com',
                'fecha_verificacion_email' => NULL,
                'token_email_confirmation' => 'ucA8UpItiUvmnE6X3ucVNvxujHS0tx',
                'password' => '$2y$10$eUX5DS/AH263axoDMiI1cOxUbVOcxX3hBbVqYnUqWf/A9x1czCufi',
                'imagen' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-10-07 04:22:32',
                'updated_at' => '2019-10-30 12:28:37',
                'deleted_at' => '2019-10-30 12:28:37',
                'id_rol' => 3,
            ),
            3 => 
            array (
                'id' => 38,
                'nombre' => 'Juan Pablo Urbina',
                'email' => 'juanpablo@gmail.com',
                'fecha_verificacion_email' => NULL,
                'token_email_confirmation' => 'F3q05yPyGEpWtpEzvw7p15JIpFPU9L',
                'password' => '$2y$10$1dfM.1MMmYedO89dPqoGquYyNHy9qEagXnQqm70JfhUyyKQes.ry2',
                'imagen' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-10-07 05:16:03',
                'updated_at' => '2019-10-07 05:16:03',
                'deleted_at' => NULL,
                'id_rol' => 3,
            ),
            4 => 
            array (
                'id' => 64,
                'nombre' => 'Israel Pérez',
                'email' => 'isramael9@hotmail.com',
                'fecha_verificacion_email' => '2019-10-30 09:38:17',
                'token_email_confirmation' => NULL,
                'password' => '$2y$10$bq1ObXr92r/sJbvO/ocQyuZJO62y4k/.neFEBmg.LlHWeLmnNwruK',
                'imagen' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-10-30 09:37:19',
                'updated_at' => '2019-10-30 09:38:17',
                'deleted_at' => NULL,
                'id_rol' => 3,
            ),
            5 => 
            array (
                'id' => 65,
                'nombre' => 'Berta Quintanilla',
                'email' => 'berta.quintanilla@fundacionvictoria.org.ni',
                'fecha_verificacion_email' => '2019-10-30 09:38:36',
                'token_email_confirmation' => NULL,
                'password' => '$2y$10$0zuZT5VPQS8QR7Yf5bKjlOyxORwhUNyFFoZFzv..3mV9d5sb/6gbu',
                'imagen' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-10-30 09:37:38',
                'updated_at' => '2019-10-30 09:38:36',
                'deleted_at' => NULL,
                'id_rol' => 3,
            ),
            6 => 
            array (
                'id' => 66,
                'nombre' => 'Danelia Rebeca Canales Baldizón',
                'email' => 'daneliacbaldizon@gmail.com',
                'fecha_verificacion_email' => '2019-10-30 10:45:23',
                'token_email_confirmation' => NULL,
                'password' => '$2y$10$6.5xkTGe3lZGAQMRB9zSuON/8BfDwurOytdYhxoYtx.FitdIpACna',
                'imagen' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-10-30 09:38:49',
                'updated_at' => '2019-10-30 10:45:23',
                'deleted_at' => NULL,
                'id_rol' => 3,
            ),
            7 => 
            array (
                'id' => 72,
                'nombre' => 'JOSE BERCIAN',
                'email' => 'njbercian@hotmail.com',
                'fecha_verificacion_email' => NULL,
                'token_email_confirmation' => '5yEJxxFbfm465Sm3em6eaUhQHRvPeZ',
                'password' => '$2y$10$yup4hG9Y1VSrmeMgtN.av.9YG0MGzqGV8gUNguoSQvVvfaQlSRsw6',
                'imagen' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-10-30 11:15:31',
                'updated_at' => '2019-10-30 11:15:31',
                'deleted_at' => NULL,
                'id_rol' => 3,
            ),
            8 => 
            array (
                'id' => 73,
                'nombre' => 'Jordan Antonio Talavera Carcamo',
                'email' => 'desarrollohumanocetis@gmail.com',
                'fecha_verificacion_email' => '2019-10-30 12:00:48',
                'token_email_confirmation' => NULL,
                'password' => '$2y$10$3h1evyxd7QGzY1PjeNA6Ye5hjTblGNtv0gjmz1e3KhKBAjI1jaVUG',
                'imagen' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-10-30 11:16:46',
                'updated_at' => '2019-10-30 15:19:00',
                'deleted_at' => NULL,
                'id_rol' => 5,
            ),
            9 => 
            array (
                'id' => 74,
                'nombre' => 'GEMA HERNANDEZ',
                'email' => 'ghernandez@fabretto.org',
                'fecha_verificacion_email' => NULL,
                'token_email_confirmation' => 'Hw0K041SyFAF45DoyqlXSKRJMDdWia',
                'password' => '$2y$10$ysAGUhYHiPfOLY5MJv2S2uq7C9/SxaiiutV7J7o3b729v/32Ml1.m',
                'imagen' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-10-30 11:18:24',
                'updated_at' => '2019-10-30 11:18:24',
                'deleted_at' => NULL,
                'id_rol' => 3,
            ),
            10 => 
            array (
                'id' => 75,
                'nombre' => 'Cora Isabel Gaitán',
                'email' => 'academiskorisa@gmail.com',
                'fecha_verificacion_email' => NULL,
                'token_email_confirmation' => 'WfJbOWjRM2jL0k4p1TpVmrXudKhdkB',
                'password' => '$2y$10$ghlR3FjTABI/nH8h3bqyWu88IeQQmjPHd.C6cPtAmkejKiUpeQXZC',
                'imagen' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-10-30 11:18:59',
                'updated_at' => '2019-10-30 11:18:59',
                'deleted_at' => NULL,
                'id_rol' => 3,
            ),
            11 => 
            array (
                'id' => 76,
                'nombre' => 'yamileth del carmen Guevara Guido',
                'email' => 'yguevaraguido@gmail.com',
                'fecha_verificacion_email' => NULL,
                'token_email_confirmation' => 'zm3eAKttZSn5oCK8ibD0oxxn0ceTfa',
                'password' => '$2y$10$liRmXAK/BzwwusPmh8tXPe.zfrc6ePO.8kHyy71KTL5n7W4Eki7le',
                'imagen' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-10-30 11:19:54',
                'updated_at' => '2019-10-30 11:19:54',
                'deleted_at' => NULL,
                'id_rol' => 3,
            ),
            12 => 
            array (
                'id' => 77,
                'nombre' => 'Gabriela Margarita Ñurinda López',
                'email' => 'urindalpez@yahoo.es',
                'fecha_verificacion_email' => NULL,
                'token_email_confirmation' => 'OehJg0zO2IvAQcZajiX1EXkF0VbbYX',
                'password' => '$2y$10$RACDj2AdvZsHSSdHs/jLreRBaxt/v7.UHit8SU460gpdwB84SW7Rm',
                'imagen' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-10-30 11:20:05',
                'updated_at' => '2019-10-30 11:20:05',
                'deleted_at' => NULL,
                'id_rol' => 3,
            ),
            13 => 
            array (
                'id' => 78,
                'nombre' => 'Keila Miranda Rodriguez',
                'email' => 'trabajosocialcet@hzacariasguerra.org.ni',
                'fecha_verificacion_email' => NULL,
                'token_email_confirmation' => 'awtLoAlZh3NKwD17OYwdJDnWEHlEae',
                'password' => '$2y$10$DFnGaXG542BSbQYpcw8yFetctDPV7whu3eARIZ6oDBdaG6icPNabm',
                'imagen' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-10-30 11:21:19',
                'updated_at' => '2019-10-30 11:21:19',
                'deleted_at' => NULL,
                'id_rol' => 3,
            ),
            14 => 
            array (
                'id' => 79,
                'nombre' => 'Karla Vanessa López Téllez',
                'email' => 'klopeztellez@yahoo.com',
                'fecha_verificacion_email' => '2019-10-30 15:05:11',
                'token_email_confirmation' => NULL,
                'password' => '$2y$10$3h1evyxd7QGzY1PjeNA6Ye5hjTblGNtv0gjmz1e3KhKBAjI1jaVUG',
                'imagen' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-10-30 11:21:21',
                'updated_at' => '2019-10-30 15:05:11',
                'deleted_at' => NULL,
                'id_rol' => 3,
            ),
            15 => 
            array (
                'id' => 80,
                'nombre' => 'Lester Deybi Escoto Peralta',
                'email' => 'deyviperalta@hotmail.com',
                'fecha_verificacion_email' => NULL,
                'token_email_confirmation' => '0YSfJvuB3PAbUJ38FHYMlBDRDy1lJW',
                'password' => '$2y$10$hcSbYsmjN6y9GXR/eTJ7u.TkKWhMs3A23yXXqA4gspAXMyIncWMzW',
                'imagen' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-10-30 11:21:34',
                'updated_at' => '2019-10-30 11:21:34',
                'deleted_at' => NULL,
                'id_rol' => 3,
            ),
            16 => 
            array (
                'id' => 81,
                'nombre' => 'Heysell Gertrudis Montenegro Barrera',
                'email' => 'heysellbarrera@outlook.com',
                'fecha_verificacion_email' => NULL,
                'token_email_confirmation' => '0QDaPL4IwgOPi88Q9CTurn4CMDHKc3',
                'password' => '$2y$10$QJpeAdLKFdiIbIL18VWJaObchdjuFWQ.KbNGlo1sUm21xTHY0wLsG',
                'imagen' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-10-30 11:24:12',
                'updated_at' => '2019-10-30 11:24:12',
                'deleted_at' => NULL,
                'id_rol' => 3,
            ),
            17 => 
            array (
                'id' => 82,
                'nombre' => 'Ronald Antonio Navarrete Lorio',
                'email' => 'yn1ran@gmail.com',
                'fecha_verificacion_email' => NULL,
                'token_email_confirmation' => 'VVJGEWOBU9ikfC7Q5OhGyjfZMdwPFI',
                'password' => '$2y$10$hOjjlUQ60qvJt.QEXdM04O7oF9qtY5g8o0VUEgE/faj9j5zYhnESu',
                'imagen' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-10-30 11:24:23',
                'updated_at' => '2019-10-30 11:24:23',
                'deleted_at' => NULL,
                'id_rol' => 3,
            ),
            18 => 
            array (
                'id' => 83,
                'nombre' => 'CaroLiss Centeno',
                'email' => 'carol_centeno@hotmail.com',
                'fecha_verificacion_email' => '2019-10-30 11:41:05',
                'token_email_confirmation' => NULL,
                'password' => '$2y$10$sBZLbUvnkAaK2OLYW4mshestWXhQN.yq9tQrkGg59m5i39jlxAkhS',
                'imagen' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-10-30 11:25:02',
                'updated_at' => '2019-10-30 11:41:05',
                'deleted_at' => NULL,
                'id_rol' => 3,
            ),
            19 => 
            array (
                'id' => 85,
                'nombre' => 'Meyling  Gioconda Hernández Silva',
                'email' => 'mey160308@gmail.com',
                'fecha_verificacion_email' => NULL,
                'token_email_confirmation' => 'pMeOZcXcOZkb73aLlcoe0c1S8sHmGQ',
                'password' => '$2y$10$DtZ1UoP.c0OHtEnA1kIi0u1HPIoBMERim1kPsgrmKxWRsmIj1gvNa',
                'imagen' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-10-30 11:26:01',
                'updated_at' => '2019-10-30 11:26:01',
                'deleted_at' => NULL,
                'id_rol' => 3,
            ),
            20 => 
            array (
                'id' => 87,
                'nombre' => 'Juan Antonio Palacios Silva',
                'email' => 'juan.silva@cuculmeca.org',
                'fecha_verificacion_email' => NULL,
                'token_email_confirmation' => 'L5rRZXXbM8BIjwoQt4eMPTBXjmF6w6',
                'password' => '$2y$10$v.yXQcmLR4J6RNZP64WGKu72.Hg2CRJ.TNfbMZuC8lxrCKpeNtv9u',
                'imagen' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-10-30 11:27:43',
                'updated_at' => '2019-10-30 11:27:43',
                'deleted_at' => NULL,
                'id_rol' => 3,
            ),
            21 => 
            array (
                'id' => 88,
                'nombre' => 'Edison Josué Flores Zamora',
                'email' => 'edisonflores1997@outlook.com',
                'fecha_verificacion_email' => NULL,
                'token_email_confirmation' => 'oIh77bswqPCFwThrp9zQfX0yAaACMe',
                'password' => '$2y$10$Gip0ZqieiE9j.eBUF.fbg.9cXMPUvK12JD3rzhBhF9XRNZW421SG2',
                'imagen' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-10-30 11:28:00',
                'updated_at' => '2019-10-30 11:28:00',
                'deleted_at' => NULL,
                'id_rol' => 3,
            ),
            22 => 
            array (
                'id' => 89,
                'nombre' => 'Josè Julian Dìaz Diaz',
                'email' => 'jdiaz@inprhusomoto.org',
                'fecha_verificacion_email' => NULL,
                'token_email_confirmation' => '6GJYs9mijGJ1BXseffj0gWoMEvehJg',
                'password' => '$2y$10$O57A9G4blNsAi3BlA9.ws.ZGGMY5C97bolY3od7ahm0u/WR0oGCvW',
                'imagen' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-10-30 11:34:27',
                'updated_at' => '2020-02-25 06:01:36',
                'deleted_at' => '2020-02-25 06:01:36',
                'id_rol' => 3,
            ),
            23 => 
            array (
                'id' => 90,
                'nombre' => 'Xiomara del Carmen Obando Ruiz',
                'email' => 'xruiz@inprhusomoto.org',
                'fecha_verificacion_email' => NULL,
                'token_email_confirmation' => 'blkBVfJe4M7khndHzENs3WfqN2q7m0',
                'password' => '$2y$10$zQVhpyAk8JLR4VdcmproJuc61XkF8iy.S/KHSFqCZlg05aT3D8NXa',
                'imagen' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-10-30 11:34:29',
                'updated_at' => '2019-10-30 11:34:29',
                'deleted_at' => NULL,
                'id_rol' => 3,
            ),
            24 => 
            array (
                'id' => 92,
                'nombre' => 'Luis Adolfo González Roque',
                'email' => 'gonzalezluis0706@gmail.com',
                'fecha_verificacion_email' => NULL,
                'token_email_confirmation' => 'L5JZs5OXgQaTruBvkPjxs3OxUITpuN',
                'password' => '$2y$10$d2nf14aRVbgpTsJ0RaRZGudONwudtEs2ZbfNcdPjrAQmKrjNsw6C.',
                'imagen' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-10-30 11:40:24',
                'updated_at' => '2019-10-30 11:40:24',
                'deleted_at' => NULL,
                'id_rol' => 3,
            ),
            25 => 
            array (
                'id' => 93,
                'nombre' => 'Carlos Zambrana',
                'email' => 'czambrana1487@innovactioncorp.com',
                'fecha_verificacion_email' => '2019-11-05 14:22:30',
                'token_email_confirmation' => NULL,
                'password' => '$2y$10$EeIjdLnwaY.fzKI5DOv3b.23wisXxjt3slv7rKERHK7WiPPYK3hYC',
                'imagen' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-10-30 11:40:54',
                'updated_at' => '2019-11-24 20:43:19',
                'deleted_at' => NULL,
                'id_rol' => 2,
            ),
            26 => 
            array (
                'id' => 94,
                'nombre' => 'Erika Melissa Dávila',
                'email' => 'erikameliss@yahoo.com.mx',
                'fecha_verificacion_email' => NULL,
                'token_email_confirmation' => 'XUoCIiSPwmR5rUBlJVdOmM1HfbVFHG',
                'password' => '$2y$10$1m1RFsz0BNP4/HhwwAKXPugfNnhu14d7TCzRjnRv2EBK5hb9UONAq',
                'imagen' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-10-30 11:42:22',
                'updated_at' => '2019-10-30 11:42:22',
                'deleted_at' => NULL,
                'id_rol' => 3,
            ),
            27 => 
            array (
                'id' => 95,
                'nombre' => 'Lurys Yulieth Herrera Castro',
                'email' => 'herrera_yulieth@yahoo.com',
                'fecha_verificacion_email' => NULL,
                'token_email_confirmation' => 'E4BcDAAZ5XYfQ02Ajhl3b6cg7YDIVy',
                'password' => '$2y$10$Nunqe8EotMtdIVShs9Mqr.83KRW91M1xleut6w5c.inCDkbWn5/ea',
                'imagen' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-10-30 11:49:09',
                'updated_at' => '2019-10-30 11:49:09',
                'deleted_at' => NULL,
                'id_rol' => 3,
            ),
            28 => 
            array (
                'id' => 96,
                'nombre' => 'Darling Afrania Sauning Herrera',
                'email' => 'afrania.sauning@cuculmeca.org',
                'fecha_verificacion_email' => '2019-10-31 09:30:38',
                'token_email_confirmation' => NULL,
                'password' => '$2y$10$3h1evyxd7QGzY1PjeNA6Ye5hjTblGNtv0gjmz1e3KhKBAjI1jaVUG',
                'imagen' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-10-30 11:54:35',
                'updated_at' => '2019-10-31 09:30:38',
                'deleted_at' => NULL,
                'id_rol' => 3,
            ),
            29 => 
            array (
                'id' => 97,
                'nombre' => 'Marcio Munguía Pavon',
                'email' => 'chefmarcio75@gmail.com',
                'fecha_verificacion_email' => NULL,
                'token_email_confirmation' => 'vZUOJY6MMYAdJ5eSozULDObk9XHyk7',
                'password' => '$2y$10$1sbL/j460NS8VKW01PN8O.CbNfhh/MW6JPj38c.NyjRI/h5ZXsWSW',
                'imagen' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-10-30 12:10:59',
                'updated_at' => '2019-10-30 12:10:59',
                'deleted_at' => NULL,
                'id_rol' => 3,
            ),
            30 => 
            array (
                'id' => 105,
                'nombre' => 'Johanna Sanchez Navarro',
                'email' => 'johanna.sanchez@swisscontact.org',
                'fecha_verificacion_email' => '2019-11-24 21:08:56',
                'token_email_confirmation' => NULL,
                'password' => '$2y$10$n.e8elJabqY9ZkQqSBi6z.KPCUGB8j3Pnc/gI6HK1odcJm7KqI4eu',
                'imagen' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-10-31 12:13:29',
                'updated_at' => '2019-11-24 21:08:56',
                'deleted_at' => NULL,
                'id_rol' => 2,
            ),
            31 => 
            array (
                'id' => 110,
                'nombre' => 'Ricardo Fernández',
                'email' => 'ricardo.fernandez@swisscontact.org',
                'fecha_verificacion_email' => '2019-10-31 12:18:59',
                'token_email_confirmation' => NULL,
                'password' => '$2y$10$lF4rzoHIWCpGSUeEywa98OLcBRWkvqrwAzhXWT8BtgeH/HbkSEB5q',
                'imagen' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-10-31 12:16:04',
                'updated_at' => '2019-11-24 20:33:56',
                'deleted_at' => NULL,
                'id_rol' => 2,
            ),
            32 => 
            array (
                'id' => 112,
                'nombre' => 'Heysell Gertrudis Montenegro Barrera',
                'email' => 'heysell.mbarrera@gmail.com',
                'fecha_verificacion_email' => NULL,
                'token_email_confirmation' => 'ek9JU86EGk4E5cFRdlE3GsEOrXZkhO',
                'password' => '$2y$10$6l11t7wF6pLG4MX1KBV8I.c/PX8GIMh0uddrP8tOXaQEX492Pwxxy',
                'imagen' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-11-04 11:45:00',
                'updated_at' => '2019-11-04 11:45:00',
                'deleted_at' => NULL,
                'id_rol' => 3,
            ),
            33 => 
            array (
                'id' => 129,
                'nombre' => 'Carlos Zambrana',
                'email' => 'caguzata@yahoo.com',
                'fecha_verificacion_email' => NULL,
                'token_email_confirmation' => 'BVeHh37GaJwqyvctlrb1RDLuKzFjUZ',
                'password' => '$2y$10$Nj2Chm6I7nONYWha/okNiO.qBgdP7NtdwDe5cn32WgrTj6yGrgdJC',
                'imagen' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-11-24 12:24:47',
                'updated_at' => '2020-02-06 07:28:11',
                'deleted_at' => '2020-02-06 07:28:11',
                'id_rol' => 5,
            ),
            34 => 
            array (
                'id' => 137,
                'nombre' => 'Charlie Zambrana',
                'email' => 'cazam_87@hotmail.com',
                'fecha_verificacion_email' => NULL,
                'token_email_confirmation' => 'WaN8HkXA8Hj6m4iH1fVxX1KaA8tdxY',
                'password' => '$2y$10$qJRHjZNjtY.ZY8asxxEK6Oy6SEdmm1oidGREPOzsnE8Zu5.PsWYw2',
                'imagen' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-11-24 21:31:46',
                'updated_at' => '2020-02-25 06:00:00',
                'deleted_at' => '2020-02-25 06:00:00',
                'id_rol' => 5,
            ),
            35 => 
            array (
                'id' => 138,
                'nombre' => 'Ismael Reyes',
                'email' => 'ireyes@innovactioncorp.com',
                'fecha_verificacion_email' => '2020-02-04 10:48:41',
                'token_email_confirmation' => NULL,
                'password' => '$2y$10$bG3xdHvgKwI7mkYnezpJduOSRIQgCIi0KnD/h1AzwdPsf8QWQSP.S',
                'imagen' => NULL,
                'remember_token' => NULL,
                'created_at' => '2019-11-24 21:41:00',
                'updated_at' => '2020-02-06 05:34:46',
                'deleted_at' => NULL,
                'id_rol' => 4,
            ),
            36 => 
            array (
                'id' => 142,
                'nombre' => 'Ana Carolina Alfaro Peña',
                'email' => 'anacalfaro@janicaragua.org',
                'fecha_verificacion_email' => NULL,
                'token_email_confirmation' => 'RjVieMcYAA5MTq2WmTYFoOQxmSslp5',
                'password' => '$2y$10$XtRxyaYiVfdbcpIBcsyIUOZp3Pz9DxEDtCDpljAnNlBV2ESrB35yS',
                'imagen' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-02-13 09:32:10',
                'updated_at' => '2020-02-13 09:32:10',
                'deleted_at' => NULL,
                'id_rol' => 4,
            ),
            37 => 
            array (
                'id' => 143,
                'nombre' => 'Adilia Muñoz Rios',
                'email' => 'adilia.rios@grupocoauto.com',
                'fecha_verificacion_email' => '2020-02-29 01:19:21',
                'token_email_confirmation' => NULL,
                'password' => '$2y$10$pC305B3s5hAfgWKz/eT.KebsHGM45GY1v1mXt3ESW6wYCNZu405cq',
                'imagen' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-02-13 09:32:50',
                'updated_at' => '2020-02-29 01:19:21',
                'deleted_at' => NULL,
                'id_rol' => 4,
            ),
            38 => 
            array (
                'id' => 144,
                'nombre' => 'Karla Pérez Alonzo',
                'email' => 'capacitacion@ccsn.org.ni',
                'fecha_verificacion_email' => '2020-02-24 09:56:12',
                'token_email_confirmation' => NULL,
                'password' => '$2y$10$SBPYr7Ma9dzhkAzow/IEferRS.tm4W.nPJ3Nzl837UIboqaTRps7K',
                'imagen' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-02-24 09:42:39',
                'updated_at' => '2020-02-24 09:56:12',
                'deleted_at' => NULL,
                'id_rol' => 4,
            ),
            39 => 
            array (
                'id' => 145,
                'nombre' => 'Juan Ramón Centeno',
                'email' => 'capacitacion@ipls-lasalle.org',
                'fecha_verificacion_email' => '2020-02-28 03:09:33',
                'token_email_confirmation' => NULL,
                'password' => '$2y$10$Fud8teRTDlpzhGWiM4hKtuhP5TLEP5NARDX17Gx//N4IcH44Znudu',
                'imagen' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-02-24 10:07:07',
                'updated_at' => '2020-02-28 03:09:33',
                'deleted_at' => NULL,
                'id_rol' => 4,
            ),
            40 => 
            array (
                'id' => 146,
                'nombre' => 'Francisco Baez',
                'email' => 'baezfpsicologo@gmail.com',
                'fecha_verificacion_email' => NULL,
                'token_email_confirmation' => '14gHfAgGaArgCMR8AyhQU1RfwVDxlg',
                'password' => '$2y$10$3nSZBIgxIB2LhucaWhLdVuFvKYW1thzHWqHMN7E.3m3MasRdUCtgm',
                'imagen' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-02-25 04:25:44',
                'updated_at' => '2020-02-25 04:25:44',
                'deleted_at' => NULL,
                'id_rol' => 4,
            ),
            41 => 
            array (
                'id' => 147,
                'nombre' => 'Verónica Dávila Ortega',
                'email' => 'verdav79@gmail.com',
                'fecha_verificacion_email' => NULL,
                'token_email_confirmation' => 'uDhNXKQnIJSSh6WJPNX4uARivWzaky',
                'password' => '$2y$10$KkWNJgsgJ7ZvGgiLcTwbG./af9EJ6ZXDuUGHWmKpS3Am5b75ERKzK',
                'imagen' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-02-25 05:38:02',
                'updated_at' => '2020-02-25 05:56:35',
                'deleted_at' => NULL,
                'id_rol' => 4,
            ),
            42 => 
            array (
                'id' => 148,
                'nombre' => 'Yesenia Salinas',
                'email' => 'educaciontecnica@feyalegria.org.ni',
                'fecha_verificacion_email' => NULL,
                'token_email_confirmation' => '3kBQ0GeveEoETQlTavwyZ4UfKzMXhh',
                'password' => '$2y$10$jPv6lFFUG.ho4Ir0h.InIe1Uw.uML3sx0154LbndrMsI4xh.CnJEC',
                'imagen' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-02-28 09:38:31',
                'updated_at' => '2020-02-28 09:38:31',
                'deleted_at' => NULL,
                'id_rol' => 4,
            ),
            43 => 
            array (
                'id' => 149,
                'nombre' => 'Freddy Palacios',
                'email' => 'fredyjrjsn@yahoo.com',
                'fecha_verificacion_email' => '2020-03-04 06:34:48',
                'token_email_confirmation' => NULL,
                'password' => '$2y$10$6LKfpylKm4SfI1gmNtpERuJmBSW4prWQkVhNierJOPMYT4lDW8Va2',
                'imagen' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-03-04 05:45:33',
                'updated_at' => '2020-03-04 06:34:48',
                'deleted_at' => NULL,
                'id_rol' => 3,
            ),
        ));
        
        
    }
}